import { Dimensions } from 'react-native';
import { CityData } from './types';

export const { width, height } = Dimensions.get('window');

export const SAMPLE_CITIES: CityData[] = [
  // United States
  { name: 'New York', country: 'United States' },
  { name: 'Los Angeles', country: 'United States' },
  { name: 'Chicago', country: 'United States' },
  { name: 'Houston', country: 'United States' },
  { name: 'Phoenix', country: 'United States' },
  { name: 'Philadelphia', country: 'United States' },
  { name: 'San Antonio', country: 'United States' },
  { name: 'San Diego', country: 'United States' },
  { name: 'Dallas', country: 'United States' },
  { name: 'San Jose', country: 'United States' },
  { name: 'Austin', country: 'United States' },
  { name: 'Jacksonville', country: 'United States' },
  { name: 'San Francisco', country: 'United States' },
  { name: 'Columbus', country: 'United States' },
  { name: 'Seattle', country: 'United States' },
  { name: 'Denver', country: 'United States' },
  { name: 'Washington', country: 'United States' },
  { name: 'Boston', country: 'United States' },
  { name: 'Nashville', country: 'United States' },
  { name: 'Detroit', country: 'United States' },
  { name: 'Portland', country: 'United States' },
  { name: 'Las Vegas', country: 'United States' },
  { name: 'Memphis', country: 'United States' },
  { name: 'Louisville', country: 'United States' },
  { name: 'Baltimore', country: 'United States' },
  { name: 'Milwaukee', country: 'United States' },
  { name: 'Albuquerque', country: 'United States' },
  { name: 'Tucson', country: 'United States' },
  { name: 'Sacramento', country: 'United States' },
  { name: 'Atlanta', country: 'United States' },
  { name: 'Miami', country: 'United States' },
  { name: 'Minneapolis', country: 'United States' },
  { name: 'Cleveland', country: 'United States' },
  // United Kingdom
  { name: 'London', country: 'United Kingdom' },
  { name: 'Manchester', country: 'United Kingdom' },
  { name: 'Birmingham', country: 'United Kingdom' },
  { name: 'Liverpool', country: 'United Kingdom' },
  { name: 'Leeds', country: 'United Kingdom' },
  { name: 'Glasgow', country: 'United Kingdom' },
  { name: 'Edinburgh', country: 'United Kingdom' },
  { name: 'Bristol', country: 'United Kingdom' },
  // France
  { name: 'Paris', country: 'France' },
  { name: 'Lyon', country: 'France' },
  { name: 'Marseille', country: 'France' },
  { name: 'Toulouse', country: 'France' },
  { name: 'Nice', country: 'France' },
  { name: 'Nantes', country: 'France' },
  { name: 'Strasbourg', country: 'France' },
  { name: 'Montpellier', country: 'France' },
  // Germany
  { name: 'Berlin', country: 'Germany' },
  { name: 'Munich', country: 'Germany' },
  { name: 'Hamburg', country: 'Germany' },
  { name: 'Frankfurt', country: 'Germany' },
  { name: 'Cologne', country: 'Germany' },
  { name: 'Stuttgart', country: 'Germany' },
  { name: 'Düsseldorf', country: 'Germany' },
  { name: 'Dortmund', country: 'Germany' },
  // Italy
  { name: 'Rome', country: 'Italy' },
  { name: 'Milan', country: 'Italy' },
  { name: 'Naples', country: 'Italy' },
  { name: 'Turin', country: 'Italy' },
  { name: 'Palermo', country: 'Italy' },
  { name: 'Genoa', country: 'Italy' },
  { name: 'Bologna', country: 'Italy' },
  { name: 'Florence', country: 'Italy' },
  // Spain
  { name: 'Madrid', country: 'Spain' },
  { name: 'Barcelona', country: 'Spain' },
  { name: 'Valencia', country: 'Spain' },
  { name: 'Seville', country: 'Spain' },
  { name: 'Zaragoza', country: 'Spain' },
  { name: 'Málaga', country: 'Spain' },
  { name: 'Murcia', country: 'Spain' },
  { name: 'Palma', country: 'Spain' },
  // Canada
  { name: 'Toronto', country: 'Canada' },
  { name: 'Montreal', country: 'Canada' },
  { name: 'Vancouver', country: 'Canada' },
  { name: 'Calgary', country: 'Canada' },
  { name: 'Edmonton', country: 'Canada' },
  { name: 'Ottawa', country: 'Canada' },
  { name: 'Winnipeg', country: 'Canada' },
  { name: 'Quebec City', country: 'Canada' },
  // Australia
  { name: 'Sydney', country: 'Australia' },
  { name: 'Melbourne', country: 'Australia' },
  { name: 'Brisbane', country: 'Australia' },
  { name: 'Perth', country: 'Australia' },
  { name: 'Adelaide', country: 'Australia' },
  { name: 'Gold Coast', country: 'Australia' },
  { name: 'Newcastle', country: 'Australia' },
  { name: 'Canberra', country: 'Australia' },
  // Japan
  { name: 'Tokyo', country: 'Japan' },
  { name: 'Yokohama', country: 'Japan' },
  { name: 'Osaka', country: 'Japan' },
  { name: 'Nagoya', country: 'Japan' },
  { name: 'Sapporo', country: 'Japan' },
  { name: 'Fukuoka', country: 'Japan' },
  { name: 'Kobe', country: 'Japan' },
  { name: 'Kyoto', country: 'Japan' },
  // Other countries
  { name: 'Mexico City', country: 'Mexico' },
  { name: 'São Paulo', country: 'Brazil' },
  { name: 'Rio de Janeiro', country: 'Brazil' },
  { name: 'Buenos Aires', country: 'Argentina' },
  { name: 'Moscow', country: 'Russia', nameRu: 'Москва' },
  { name: 'Saint Petersburg', country: 'Russia', nameRu: 'Санкт-Петербург' },
  { name: 'Novosibirsk', country: 'Russia', nameRu: 'Новосибирск' },
  { name: 'Yekaterinburg', country: 'Russia', nameRu: 'Екатеринбург' },
  { name: 'Kazan', country: 'Russia', nameRu: 'Казань' },
  { name: 'Nizhny Novgorod', country: 'Russia', nameRu: 'Нижний Новгород' },
  { name: 'Chelyabinsk', country: 'Russia', nameRu: 'Челябинск' },
  { name: 'Samara', country: 'Russia', nameRu: 'Самара' },
  { name: 'Omsk', country: 'Russia', nameRu: 'Омск' },
  { name: 'Rostov-on-Don', country: 'Russia', nameRu: 'Ростов-на-Дону' },
  { name: 'Ufa', country: 'Russia', nameRu: 'Уфа' },
  { name: 'Krasnoyarsk', country: 'Russia', nameRu: 'Красноярск' },
  { name: 'Voronezh', country: 'Russia', nameRu: 'Воронеж' },
  { name: 'Perm', country: 'Russia', nameRu: 'Пермь' },
  { name: 'Volgograd', country: 'Russia', nameRu: 'Волгоград' },
  { name: 'Krasnodar', country: 'Russia', nameRu: 'Краснодар' },
  { name: 'Saratov', country: 'Russia', nameRu: 'Саратов' },
  { name: 'Tyumen', country: 'Russia', nameRu: 'Тюмень' },
  { name: 'Tolyatti', country: 'Russia', nameRu: 'Тольятти' },
  { name: 'Izhevsk', country: 'Russia', nameRu: 'Ижевск' },
  { name: 'Barnaul', country: 'Russia', nameRu: 'Барнаул' },
  { name: 'Ulyanovsk', country: 'Russia', nameRu: 'Ульяновск' },
  { name: 'Irkutsk', country: 'Russia', nameRu: 'Иркутск' },
  { name: 'Khabarovsk', country: 'Russia', nameRu: 'Хабаровск' },
  { name: 'Yaroslavl', country: 'Russia', nameRu: 'Ярославль' },
  { name: 'Vladivostok', country: 'Russia', nameRu: 'Владивосток' },
  { name: 'Makhachkala', country: 'Russia', nameRu: 'Махачкала' },
  { name: 'Tomsk', country: 'Russia', nameRu: 'Томск' },
  { name: 'Orenburg', country: 'Russia', nameRu: 'Оренбург' },
  { name: 'Kemerovo', country: 'Russia', nameRu: 'Кемерово' },
  { name: 'Amsterdam', country: 'Netherlands' },
  { name: 'Rotterdam', country: 'Netherlands' },
  { name: 'Brussels', country: 'Belgium' },
  { name: 'Vienna', country: 'Austria' },
  { name: 'Zurich', country: 'Switzerland' },
  { name: 'Stockholm', country: 'Sweden' },
  { name: 'Copenhagen', country: 'Denmark' },
  { name: 'Oslo', country: 'Norway' },
  { name: 'Helsinki', country: 'Finland' },
  { name: 'Dublin', country: 'Ireland' },
  { name: 'Lisbon', country: 'Portugal' },
  { name: 'Athens', country: 'Greece' },
  { name: 'Warsaw', country: 'Poland' },
  { name: 'Prague', country: 'Czech Republic' },
  { name: 'Budapest', country: 'Hungary' },
  { name: 'Bucharest', country: 'Romania' },
  { name: 'Istanbul', country: 'Turkey' },
  { name: 'Cairo', country: 'Egypt' },
  { name: 'Johannesburg', country: 'South Africa' },
  { name: 'Cape Town', country: 'South Africa' },
  { name: 'Dubai', country: 'United Arab Emirates' },
  { name: 'Singapore', country: 'Singapore' },
  { name: 'Bangkok', country: 'Thailand' },
  { name: 'Jakarta', country: 'Indonesia' },
  { name: 'Manila', country: 'Philippines' },
  { name: 'Seoul', country: 'South Korea' },
  { name: 'Beijing', country: 'China' },
  { name: 'Shanghai', country: 'China' },
  { name: 'Hong Kong', country: 'China' },
  { name: 'Mumbai', country: 'India' },
  { name: 'Delhi', country: 'India' },
  { name: 'Bangalore', country: 'India' },
  { name: 'Kolkata', country: 'India' },
  { name: 'Chennai', country: 'India' },
  { name: 'Hyderabad', country: 'India' },
  { name: 'Pune', country: 'India' },
  { name: 'Ahmedabad', country: 'India' },
  { name: 'Jaipur', country: 'India' },
  { name: 'Surat', country: 'India' },
  // More US cities
  { name: 'Charlotte', country: 'United States' },
  { name: 'Indianapolis', country: 'United States' },
  { name: 'San Francisco', country: 'United States' },
  { name: 'Fort Worth', country: 'United States' },
  { name: 'Oklahoma City', country: 'United States' },
  { name: 'El Paso', country: 'United States' },
  { name: 'Kansas City', country: 'United States' },
  { name: 'Tampa', country: 'United States' },
  { name: 'Raleigh', country: 'United States' },
  { name: 'Omaha', country: 'United States' },
  { name: 'Oakland', country: 'United States' },
  { name: 'Tulsa', country: 'United States' },
  { name: 'Wichita', country: 'United States' },
  { name: 'Arlington', country: 'United States' },
  { name: 'New Orleans', country: 'United States' },
  { name: 'Honolulu', country: 'United States' },
  { name: 'Anchorage', country: 'United States' },
  // More European cities
  { name: 'Barcelona', country: 'Spain' },
  { name: 'Valencia', country: 'Spain' },
  { name: 'Bilbao', country: 'Spain' },
  { name: 'Granada', country: 'Spain' },
  { name: 'Córdoba', country: 'Spain' },
  { name: 'Venice', country: 'Italy' },
  { name: 'Verona', country: 'Italy' },
  { name: 'Naples', country: 'Italy' },
  { name: 'Bari', country: 'Italy' },
  { name: 'Catania', country: 'Italy' },
  { name: 'Hamburg', country: 'Germany' },
  { name: 'Dresden', country: 'Germany' },
  { name: 'Leipzig', country: 'Germany' },
  { name: 'Hannover', country: 'Germany' },
  { name: 'Nuremberg', country: 'Germany' },
  { name: 'Lyon', country: 'France' },
  { name: 'Bordeaux', country: 'France' },
  { name: 'Lille', country: 'France' },
  { name: 'Rennes', country: 'France' },
  { name: 'Reims', country: 'France' },
  { name: 'Le Havre', country: 'France' },
  { name: 'Sheffield', country: 'United Kingdom' },
  { name: 'Newcastle', country: 'United Kingdom' },
  { name: 'Nottingham', country: 'United Kingdom' },
  { name: 'Leicester', country: 'United Kingdom' },
  { name: 'Coventry', country: 'United Kingdom' },
  { name: 'Cardiff', country: 'United Kingdom' },
  { name: 'Belfast', country: 'United Kingdom' },
  // More Asian cities
  { name: 'Kyoto', country: 'Japan' },
  { name: 'Hiroshima', country: 'Japan' },
  { name: 'Sendai', country: 'Japan' },
  { name: 'Kawasaki', country: 'Japan' },
  { name: 'Kobe', country: 'Japan' },
  { name: 'Busan', country: 'South Korea' },
  { name: 'Incheon', country: 'South Korea' },
  { name: 'Daegu', country: 'South Korea' },
  { name: 'Daejeon', country: 'South Korea' },
  { name: 'Guangzhou', country: 'China' },
  { name: 'Shenzhen', country: 'China' },
  { name: 'Chengdu', country: 'China' },
  { name: 'Hangzhou', country: 'China' },
  { name: 'Xi\'an', country: 'China' },
  { name: 'Nanjing', country: 'China' },
  { name: 'Wuhan', country: 'China' },
  { name: 'Suzhou', country: 'China' },
  { name: 'Ho Chi Minh City', country: 'Vietnam' },
  { name: 'Hanoi', country: 'Vietnam' },
  { name: 'Kuala Lumpur', country: 'Malaysia' },
  { name: 'Penang', country: 'Malaysia' },
  { name: 'Kota Kinabalu', country: 'Malaysia' },
  { name: 'Yangon', country: 'Myanmar' },
  { name: 'Phnom Penh', country: 'Cambodia' },
  { name: 'Vientiane', country: 'Laos' },
  // More Middle Eastern cities
  { name: 'Riyadh', country: 'Saudi Arabia' },
  { name: 'Jeddah', country: 'Saudi Arabia' },
  { name: 'Mecca', country: 'Saudi Arabia' },
  { name: 'Medina', country: 'Saudi Arabia' },
  { name: 'Dammam', country: 'Saudi Arabia' },
  { name: 'Abu Dhabi', country: 'United Arab Emirates' },
  { name: 'Sharjah', country: 'United Arab Emirates' },
  { name: 'Doha', country: 'Qatar' },
  { name: 'Kuwait City', country: 'Kuwait' },
  { name: 'Manama', country: 'Bahrain' },
  { name: 'Muscat', country: 'Oman' },
  { name: 'Tehran', country: 'Iran' },
  { name: 'Baghdad', country: 'Iraq' },
  { name: 'Damascus', country: 'Syria' },
  { name: 'Beirut', country: 'Lebanon' },
  { name: 'Amman', country: 'Jordan' },
  { name: 'Jerusalem', country: 'Israel' },
  { name: 'Tel Aviv', country: 'Israel' },
  { name: 'Haifa', country: 'Israel' },
  // More African cities
  { name: 'Lagos', country: 'Nigeria' },
  { name: 'Kano', country: 'Nigeria' },
  { name: 'Ibadan', country: 'Nigeria' },
  { name: 'Abuja', country: 'Nigeria' },
  { name: 'Nairobi', country: 'Kenya' },
  { name: 'Mombasa', country: 'Kenya' },
  { name: 'Dar es Salaam', country: 'Tanzania' },
  { name: 'Addis Ababa', country: 'Ethiopia' },
  { name: 'Casablanca', country: 'Morocco' },
  { name: 'Rabat', country: 'Morocco' },
  { name: 'Marrakech', country: 'Morocco' },
  { name: 'Tunis', country: 'Tunisia' },
  { name: 'Algiers', country: 'Algeria' },
  { name: 'Accra', country: 'Ghana' },
  { name: 'Kumasi', country: 'Ghana' },
  { name: 'Dakar', country: 'Senegal' },
  { name: 'Kinshasa', country: 'Democratic Republic of the Congo' },
  { name: 'Luanda', country: 'Angola' },
  { name: 'Kampala', country: 'Uganda' },
  // More Latin American cities
  { name: 'Guadalajara', country: 'Mexico' },
  { name: 'Monterrey', country: 'Mexico' },
  { name: 'Puebla', country: 'Mexico' },
  { name: 'Tijuana', country: 'Mexico' },
  { name: 'León', country: 'Mexico' },
  { name: 'Juárez', country: 'Mexico' },
  { name: 'Brasília', country: 'Brazil' },
  { name: 'Salvador', country: 'Brazil' },
  { name: 'Fortaleza', country: 'Brazil' },
  { name: 'Belo Horizonte', country: 'Brazil' },
  { name: 'Manaus', country: 'Brazil' },
  { name: 'Curitiba', country: 'Brazil' },
  { name: 'Recife', country: 'Brazil' },
  { name: 'Porto Alegre', country: 'Brazil' },
  { name: 'Córdoba', country: 'Argentina' },
  { name: 'Rosario', country: 'Argentina' },
  { name: 'Mendoza', country: 'Argentina' },
  { name: 'Santiago', country: 'Chile' },
  { name: 'Valparaíso', country: 'Chile' },
  { name: 'Lima', country: 'Peru' },
  { name: 'Bogotá', country: 'Colombia' },
  { name: 'Medellín', country: 'Colombia' },
  { name: 'Cali', country: 'Colombia' },
  { name: 'Caracas', country: 'Venezuela' },
  { name: 'Quito', country: 'Ecuador' },
  { name: 'Guayaquil', country: 'Ecuador' },
  { name: 'Montevideo', country: 'Uruguay' },
  { name: 'Asunción', country: 'Paraguay' },
  { name: 'La Paz', country: 'Bolivia' },
  { name: 'Santa Cruz', country: 'Bolivia' },
  // More Canadian cities
  { name: 'Hamilton', country: 'Canada' },
  { name: 'Kitchener', country: 'Canada' },
  { name: 'London', country: 'Canada' },
  { name: 'Halifax', country: 'Canada' },
  { name: 'Victoria', country: 'Canada' },
  { name: 'Saskatoon', country: 'Canada' },
  { name: 'Regina', country: 'Canada' },
  { name: 'St. John\'s', country: 'Canada' },
  // More Australian cities
  { name: 'Hobart', country: 'Australia' },
  { name: 'Darwin', country: 'Australia' },
  { name: 'Cairns', country: 'Australia' },
  { name: 'Townsville', country: 'Australia' },
  { name: 'Toowoomba', country: 'Australia' },
  { name: 'Ballarat', country: 'Australia' },
  { name: 'Bendigo', country: 'Australia' },
  // More cities from around the world
  { name: 'Auckland', country: 'New Zealand' },
  { name: 'Wellington', country: 'New Zealand' },
  { name: 'Christchurch', country: 'New Zealand' },
  { name: 'Dunedin', country: 'New Zealand' },
  { name: 'Arena', country: 'Various' },
  { name: 'Barcelona', country: 'Spain' },
  { name: 'Valencia', country: 'Spain' },
  { name: 'Seville', country: 'Spain' },
  { name: 'Zaragoza', country: 'Spain' },
  { name: 'Málaga', country: 'Spain' },
  { name: 'Murcia', country: 'Spain' },
  { name: 'Palma', country: 'Spain' },
  { name: 'Las Palmas', country: 'Spain' },
  { name: 'Bilbao', country: 'Spain' },
  { name: 'Alicante', country: 'Spain' },
  { name: 'Córdoba', country: 'Spain' },
  { name: 'Valladolid', country: 'Spain' },
  { name: 'Vigo', country: 'Spain' },
  { name: 'Gijón', country: 'Spain' },
  { name: 'Granada', country: 'Spain' },
  { name: 'Milano', country: 'Italy' },
  { name: 'Napoli', country: 'Italy' },
  { name: 'Torino', country: 'Italy' },
  { name: 'Palermo', country: 'Italy' },
  { name: 'Genova', country: 'Italy' },
  { name: 'Bologna', country: 'Italy' },
  { name: 'Firenze', country: 'Italy' },
  { name: 'Bari', country: 'Italy' },
  { name: 'Catania', country: 'Italy' },
  { name: 'Venezia', country: 'Italy' },
  { name: 'Verona', country: 'Italy' },
  { name: 'Messina', country: 'Italy' },
  { name: 'Padova', country: 'Italy' },
  { name: 'Trieste', country: 'Italy' },
  { name: 'Brescia', country: 'Italy' },
  { name: 'Prato', country: 'Italy' },
  { name: 'Parma', country: 'Italy' },
  { name: 'Modena', country: 'Italy' },
  { name: 'Reggio Calabria', country: 'Italy' },
  { name: 'Perugia', country: 'Italy' },
  { name: 'Livorno', country: 'Italy' },
  { name: 'Ravenna', country: 'Italy' },
  { name: 'Cagliari', country: 'Italy' },
  { name: 'Foggia', country: 'Italy' },
  { name: 'Rimini', country: 'Italy' },
  { name: 'Salerno', country: 'Italy' },
  { name: 'Ferrara', country: 'Italy' },
  { name: 'Sassari', country: 'Italy' },
  { name: 'Latina', country: 'Italy' },
  { name: 'Giugliano', country: 'Italy' },
  { name: 'Monza', country: 'Italy' },
  { name: 'Bergamo', country: 'Italy' },
  { name: 'Forlì', country: 'Italy' },
  { name: 'Trento', country: 'Italy' },
  { name: 'Vicenza', country: 'Italy' },
  { name: 'Terni', country: 'Italy' },
  { name: 'Bolzano', country: 'Italy' },
  { name: 'Novara', country: 'Italy' },
  { name: 'Piacenza', country: 'Italy' },
  { name: 'Ancona', country: 'Italy' },
  { name: 'Andria', country: 'Italy' },
  { name: 'Arezzo', country: 'Italy' },
  { name: 'Udine', country: 'Italy' },
  { name: 'Cesena', country: 'Italy' },
  { name: 'Lecce', country: 'Italy' },
  { name: 'Pesaro', country: 'Italy' },
  { name: 'La Spezia', country: 'Italy' },
  { name: 'Pisa', country: 'Italy' },
  { name: 'Guidonia', country: 'Italy' },
  { name: 'Catanzaro', country: 'Italy' },
  { name: 'Caserta', country: 'Italy' },
  { name: 'Brindisi', country: 'Italy' },
  { name: 'Pozzuoli', country: 'Italy' },
  { name: 'Marsala', country: 'Italy' },
  { name: 'Treviso', country: 'Italy' },
  { name: 'Como', country: 'Italy' },
  { name: 'Varese', country: 'Italy' },
  { name: 'Pavia', country: 'Italy' },
  { name: 'Cremona', country: 'Italy' },
  { name: 'Mantova', country: 'Italy' },
  { name: 'Pordenone', country: 'Italy' },
  { name: 'Alessandria', country: 'Italy' },
  { name: 'Asti', country: 'Italy' },
  { name: 'Imperia', country: 'Italy' },
  { name: 'Savona', country: 'Italy' },
  { name: 'Sanremo', country: 'Italy' },
  { name: 'Albenga', country: 'Italy' },
  { name: 'Ventimiglia', country: 'Italy' },
  { name: 'Bordighera', country: 'Italy' },
  { name: 'Rapallo', country: 'Italy' },
  { name: 'Chiavari', country: 'Italy' },
  { name: 'Sestri Levante', country: 'Italy' },
  { name: 'Lavagna', country: 'Italy' },
  { name: 'Santa Margherita', country: 'Italy' },
  { name: 'Portofino', country: 'Italy' },
  { name: 'Camogli', country: 'Italy' },
  { name: 'Recco', country: 'Italy' },
  { name: 'Nervi', country: 'Italy' },
  { name: 'Bogliasco', country: 'Italy' },
  { name: 'Sori', country: 'Italy' },
  { name: 'Arenzano', country: 'Italy' },
  { name: 'Cogoleto', country: 'Italy' },
  { name: 'Varazze', country: 'Italy' },
  { name: 'Celle Ligure', country: 'Italy' },
  { name: 'Spotorno', country: 'Italy' },
  { name: 'Noli', country: 'Italy' },
  { name: 'Finale Ligure', country: 'Italy' },
  { name: 'Pietra Ligure', country: 'Italy' },
  { name: 'Loano', country: 'Italy' },
  { name: 'Alassio', country: 'Italy' },
  { name: 'Laigueglia', country: 'Italy' },
  { name: 'Andora', country: 'Italy' },
  { name: 'Cervo', country: 'Italy' },
  { name: 'Diano Marina', country: 'Italy' },
  { name: 'Imperia', country: 'Italy' },
  { name: 'San Bartolomeo', country: 'Italy' },
  { name: 'Taggia', country: 'Italy' },
  { name: 'Arma di Taggia', country: 'Italy' },
  { name: 'Riva Ligure', country: 'Italy' },
  { name: 'Pompeiana', country: 'Italy' },
  { name: 'Cipressa', country: 'Italy' },
  { name: 'Costarainera', country: 'Italy' },
  { name: 'San Lorenzo al Mare', country: 'Italy' },
  { name: 'Civezza', country: 'Italy' },
  { name: 'Dolcedo', country: 'Italy' },
  { name: 'Prelà', country: 'Italy' },
  { name: 'Vasia', country: 'Italy' },
  { name: 'Pontedassio', country: 'Italy' },
  { name: 'Chiusanico', country: 'Italy' },
  { name: 'Chiusavecchia', country: 'Italy' },
  { name: 'Borgomaro', country: 'Italy' },
  { name: 'Aurigo', country: 'Italy' },
  { name: 'Rezzo', country: 'Italy' },
  { name: 'Mendatica', country: 'Italy' },
  { name: 'Cosio di Arroscia', country: 'Italy' },
  { name: 'Pieve di Teco', country: 'Italy' },
  { name: 'Ranzo', country: 'Italy' },
  { name: 'Vessalico', country: 'Italy' },
  { name: 'Cesio', country: 'Italy' },
  { name: 'Caravonica', country: 'Italy' },
  { name: 'Chiusa di Pesio', country: 'Italy' },
  { name: 'Briga Alta', country: 'Italy' },
  { name: 'Ormea', country: 'Italy' },
  { name: 'Caprauna', country: 'Italy' },
  { name: 'Alto', country: 'Italy' },
  { name: 'Aquila', country: 'Italy' },
  { name: 'Arnasco', country: 'Italy' },
  { name: 'Balestrino', country: 'Italy' },
  { name: 'Bardineto', country: 'Italy' },
  { name: 'Bergeggi', country: 'Italy' },
  { name: 'Boissano', country: 'Italy' },
  { name: 'Borghetto', country: 'Italy' },
  { name: 'Borgio', country: 'Italy' },
  { name: 'Cairo Montenotte', country: 'Italy' },
  { name: 'Calice Ligure', country: 'Italy' },
  { name: 'Calizzano', country: 'Italy' },
  { name: 'Carcare', country: 'Italy' },
  { name: 'Casanova Lerrone', country: 'Italy' },
  { name: 'Castelbianco', country: 'Italy' },
  { name: 'Castelvecchio', country: 'Italy' },
  { name: 'Celle di Macra', country: 'Italy' },
  { name: 'Cengio', country: 'Italy' },
  { name: 'Ceriale', country: 'Italy' },
  { name: 'Cisano', country: 'Italy' },
  { name: 'Cosseria', country: 'Italy' },
  { name: 'Dego', country: 'Italy' },
  { name: 'Erli', country: 'Italy' },
  { name: 'Finale Ligure', country: 'Italy' },
  { name: 'Garlenda', country: 'Italy' },
  { name: 'Giustenice', country: 'Italy' },
  { name: 'Giusvalla', country: 'Italy' },
  { name: 'Laigueglia', country: 'Italy' },
  { name: 'Loano', country: 'Italy' },
  { name: 'Magliolo', country: 'Italy' },
  { name: 'Mallare', country: 'Italy' },
  { name: 'Massimino', country: 'Italy' },
  { name: 'Millesimo', country: 'Italy' },
  { name: 'Mioglia', country: 'Italy' },
  { name: 'Murialdo', country: 'Italy' },
  { name: 'Nasino', country: 'Italy' },
  { name: 'Noli', country: 'Italy' },
  { name: 'Onzo', country: 'Italy' },
  { name: 'Orco Feglino', country: 'Italy' },
  { name: 'Ortovero', country: 'Italy' },
  { name: 'Osiglia', country: 'Italy' },
  { name: 'Pallare', country: 'Italy' },
  { name: 'Piana Crixia', country: 'Italy' },
  { name: 'Pietra Ligure', country: 'Italy' },
  { name: 'Plodio', country: 'Italy' },
  { name: 'Pontinvrea', country: 'Italy' },
  { name: 'Quiliano', country: 'Italy' },
  { name: 'Rialto', country: 'Italy' },
  { name: 'Roccavignale', country: 'Italy' },
  { name: 'Sassello', country: 'Italy' },
  { name: 'Savona', country: 'Italy' },
  { name: 'Spotorno', country: 'Italy' },
  { name: 'Stella', country: 'Italy' },
  { name: 'Stellanello', country: 'Italy' },
  { name: 'Testico', country: 'Italy' },
  { name: 'Toirano', country: 'Italy' },
  { name: 'Tovo San Giacomo', country: 'Italy' },
  { name: 'Urbe', country: 'Italy' },
  { name: 'Vado Ligure', country: 'Italy' },
  { name: 'Varazze', country: 'Italy' },
  { name: 'Vendone', country: 'Italy' },
  { name: 'Vezzi Portio', country: 'Italy' },
  { name: 'Villanova', country: 'Italy' },
  { name: 'Zuccarello', country: 'Italy' },
  { name: 'Albury', country: 'Australia' },
  // More European cities
  { name: 'Gdansk', country: 'Poland' },
  { name: 'Krakow', country: 'Poland' },
  { name: 'Wroclaw', country: 'Poland' },
  { name: 'Poznan', country: 'Poland' },
  { name: 'Lodz', country: 'Poland' },
  { name: 'Brno', country: 'Czech Republic' },
  { name: 'Ostrava', country: 'Czech Republic' },
  { name: 'Plzen', country: 'Czech Republic' },
  { name: 'Debrecen', country: 'Hungary' },
  { name: 'Szeged', country: 'Hungary' },
  { name: 'Cluj-Napoca', country: 'Romania' },
  { name: 'Timisoara', country: 'Romania' },
  { name: 'Iasi', country: 'Romania' },
  { name: 'Sofia', country: 'Bulgaria' },
  { name: 'Plovdiv', country: 'Bulgaria' },
  { name: 'Zagreb', country: 'Croatia' },
  { name: 'Split', country: 'Croatia' },
  { name: 'Belgrade', country: 'Serbia' },
  { name: 'Ljubljana', country: 'Slovenia' },
  { name: 'Bratislava', country: 'Slovakia' },
  { name: 'Vilnius', country: 'Lithuania' },
  { name: 'Riga', country: 'Latvia' },
  { name: 'Tallinn', country: 'Estonia' },
  { name: 'Reykjavik', country: 'Iceland' },
  { name: 'Luxembourg', country: 'Luxembourg' },
  { name: 'Monaco', country: 'Monaco' },
  { name: 'Andorra la Vella', country: 'Andorra' },
  { name: 'Valletta', country: 'Malta' },
  { name: 'Nicosia', country: 'Cyprus' },
  // Armenia
  { name: 'Yerevan', country: 'Armenia' },
  { name: 'Gyumri', country: 'Armenia' },
  { name: 'Vanadzor', country: 'Armenia' },
  { name: 'Vagharshapat', country: 'Armenia' },
  { name: 'Abovyan', country: 'Armenia' },
  { name: 'Kapan', country: 'Armenia' },
  { name: 'Hrazdan', country: 'Armenia' },
  { name: 'Armavir', country: 'Armenia' },
  { name: 'Goris', country: 'Armenia' },
  { name: 'Artashat', country: 'Armenia' },
  { name: 'Sevan', country: 'Armenia' },
  { name: 'Ashtarak', country: 'Armenia' },
  { name: 'Ijevan', country: 'Armenia' },
  { name: 'Dilijan', country: 'Armenia' },
  { name: 'Alaverdi', country: 'Armenia' },
  { name: 'Vardenis', country: 'Armenia' },
  { name: 'Martuni', country: 'Armenia' },
  { name: 'Masis', country: 'Armenia' },
  { name: 'Ararat', country: 'Armenia' },
  { name: 'Gavar', country: 'Armenia' },
  // Belarus
  { name: 'Minsk', country: 'Belarus' },
  { name: 'Gomel', country: 'Belarus' },
  { name: 'Mogilev', country: 'Belarus' },
  { name: 'Vitebsk', country: 'Belarus' },
  { name: 'Grodno', country: 'Belarus' },
  { name: 'Brest', country: 'Belarus' },
  { name: 'Babruysk', country: 'Belarus' },
  { name: 'Baranavichy', country: 'Belarus' },
  { name: 'Barysaw', country: 'Belarus' },
  { name: 'Pinsk', country: 'Belarus' },
  { name: 'Orsha', country: 'Belarus' },
  { name: 'Mazyr', country: 'Belarus' },
  { name: 'Salihorsk', country: 'Belarus' },
  { name: 'Navahrudak', country: 'Belarus' },
  { name: 'Maladzyechna', country: 'Belarus' },
  { name: 'Polatsk', country: 'Belarus' },
  { name: 'Lida', country: 'Belarus' },
  { name: 'Svyetlahorsk', country: 'Belarus' },
  { name: 'Zhlobin', country: 'Belarus' },
  { name: 'Slutsk', country: 'Belarus' },
  // Romania
  { name: 'Bucharest', country: 'Romania' },
  { name: 'Cluj-Napoca', country: 'Romania' },
  { name: 'Timișoara', country: 'Romania' },
  { name: 'Iași', country: 'Romania' },
  { name: 'Constanța', country: 'Romania' },
  { name: 'Craiova', country: 'Romania' },
  { name: 'Brașov', country: 'Romania' },
  { name: 'Galați', country: 'Romania' },
  { name: 'Ploiești', country: 'Romania' },
  { name: 'Oradea', country: 'Romania' },
  { name: 'Brăila', country: 'Romania' },
  { name: 'Arad', country: 'Romania' },
  { name: 'Pitești', country: 'Romania' },
  { name: 'Sibiu', country: 'Romania' },
  { name: 'Bacău', country: 'Romania' },
  { name: 'Târgu Mureș', country: 'Romania' },
  { name: 'Baia Mare', country: 'Romania' },
  { name: 'Buzău', country: 'Romania' },
  { name: 'Botoșani', country: 'Romania' },
  { name: 'Satu Mare', country: 'Romania' },
  { name: 'Râmnicu Vâlcea', country: 'Romania' },
  { name: 'Suceava', country: 'Romania' },
  { name: 'Piatra Neamț', country: 'Romania' },
  { name: 'Drobeta-Turnu Severin', country: 'Romania' },
  { name: 'Târgoviște', country: 'Romania' },
  { name: 'Focșani', country: 'Romania' },
  { name: 'Tulcea', country: 'Romania' },
  { name: 'Reșița', country: 'Romania' },
  { name: 'Călărași', country: 'Romania' },
  { name: 'Alba Iulia', country: 'Romania' },
  // More Chinese cities
  { name: 'Tianjin', country: 'China' },
  { name: 'Chongqing', country: 'China' },
  { name: 'Dongguan', country: 'China' },
  { name: 'Foshan', country: 'China' },
  { name: 'Jinan', country: 'China' },
  { name: 'Dalian', country: 'China' },
  { name: 'Qingdao', country: 'China' },
  { name: 'Xiamen', country: 'China' },
  { name: 'Kunming', country: 'China' },
  { name: 'Changsha', country: 'China' },
  { name: 'Fuzhou', country: 'China' },
  { name: 'Zhengzhou', country: 'China' },
  { name: 'Shijiazhuang', country: 'China' },
  { name: 'Harbin', country: 'China' },
  { name: 'Changchun', country: 'China' },
  { name: 'Urumqi', country: 'China' },
  { name: 'Lanzhou', country: 'China' },
  { name: 'Taiyuan', country: 'China' },
  { name: 'Hefei', country: 'China' },
  { name: 'Nanchang', country: 'China' },
  { name: 'Guiyang', country: 'China' },
  { name: 'Nanning', country: 'China' },
  { name: 'Haikou', country: 'China' },
  { name: 'Lhasa', country: 'China' },
  { name: 'Yinchuan', country: 'China' },
  { name: 'Hohhot', country: 'China' },
  { name: 'Xining', country: 'China' },
  // More Japanese cities
  { name: 'Sendai', country: 'Japan' },
  { name: 'Hiroshima', country: 'Japan' },
  { name: 'Kitakyushu', country: 'Japan' },
  { name: 'Chiba', country: 'Japan' },
  { name: 'Sakai', country: 'Japan' },
  { name: 'Niigata', country: 'Japan' },
  { name: 'Hamamatsu', country: 'Japan' },
  { name: 'Shizuoka', country: 'Japan' },
  { name: 'Okayama', country: 'Japan' },
  { name: 'Kumamoto', country: 'Japan' },
  { name: 'Kagoshima', country: 'Japan' },
  { name: 'Sagamihara', country: 'Japan' },
  { name: 'Funabashi', country: 'Japan' },
  { name: 'Hachioji', country: 'Japan' },
  { name: 'Kawaguchi', country: 'Japan' },
  { name: 'Himeji', country: 'Japan' },
  { name: 'Matsuyama', country: 'Japan' },
  { name: 'Matsudo', country: 'Japan' },
  { name: 'Nishinomiya', country: 'Japan' },
  { name: 'Kawagoe', country: 'Japan' },
  { name: 'Utsunomiya', country: 'Japan' },
  { name: 'Oita', country: 'Japan' },
  { name: 'Kurashiki', country: 'Japan' },
  { name: 'Gifu', country: 'Japan' },
  { name: 'Toyonaka', country: 'Japan' },
  { name: 'Nagano', country: 'Japan' },
  { name: 'Toyohashi', country: 'Japan' },
  { name: 'Toyama', country: 'Japan' },
  { name: 'Takamatsu', country: 'Japan' },
  // More American cities
  { name: 'Phoenix', country: 'United States' },
  { name: 'Philadelphia', country: 'United States' },
  { name: 'San Antonio', country: 'United States' },
  { name: 'San Diego', country: 'United States' },
  { name: 'Dallas', country: 'United States' },
  { name: 'San Jose', country: 'United States' },
  { name: 'Austin', country: 'United States' },
  { name: 'Jacksonville', country: 'United States' },
  { name: 'San Francisco', country: 'United States' },
  { name: 'Columbus', country: 'United States' },
  { name: 'Seattle', country: 'United States' },
  { name: 'Denver', country: 'United States' },
  { name: 'Washington', country: 'United States' },
  { name: 'Boston', country: 'United States' },
  { name: 'Nashville', country: 'United States' },
  { name: 'Detroit', country: 'United States' },
  { name: 'Portland', country: 'United States' },
  { name: 'Las Vegas', country: 'United States' },
  { name: 'Memphis', country: 'United States' },
  { name: 'Louisville', country: 'United States' },
  { name: 'Baltimore', country: 'United States' },
  { name: 'Milwaukee', country: 'United States' },
  { name: 'Albuquerque', country: 'United States' },
  { name: 'Tucson', country: 'United States' },
  { name: 'Sacramento', country: 'United States' },
  { name: 'Atlanta', country: 'United States' },
  { name: 'Miami', country: 'United States' },
  { name: 'Minneapolis', country: 'United States' },
  { name: 'Cleveland', country: 'United States' },
  { name: 'Charlotte', country: 'United States' },
  { name: 'Indianapolis', country: 'United States' },
  { name: 'Fort Worth', country: 'United States' },
  { name: 'Oklahoma City', country: 'United States' },
  { name: 'El Paso', country: 'United States' },
  { name: 'Kansas City', country: 'United States' },
  { name: 'Tampa', country: 'United States' },
  { name: 'Raleigh', country: 'United States' },
  { name: 'Omaha', country: 'United States' },
  { name: 'Oakland', country: 'United States' },
  { name: 'Tulsa', country: 'United States' },
  { name: 'Wichita', country: 'United States' },
  { name: 'Arlington', country: 'United States' },
  { name: 'New Orleans', country: 'United States' },
  { name: 'Honolulu', country: 'United States' },
  { name: 'Anchorage', country: 'United States' },
  { name: 'Buffalo', country: 'United States' },
  { name: 'Riverside', country: 'United States' },
  { name: 'St. Louis', country: 'United States' },
  { name: 'Corpus Christi', country: 'United States' },
  { name: 'Lexington', country: 'United States' },
  { name: 'Pittsburgh', country: 'United States' },
  { name: 'Stockton', country: 'United States' },
  { name: 'Cincinnati', country: 'United States' },
  { name: 'St. Paul', country: 'United States' },
  { name: 'Toledo', country: 'United States' },
  { name: 'Greensboro', country: 'United States' },
  { name: 'Newark', country: 'United States' },
  { name: 'Plano', country: 'United States' },
  { name: 'Henderson', country: 'United States' },
  { name: 'Lincoln', country: 'United States' },
  { name: 'Orlando', country: 'United States' },
  { name: 'Jersey City', country: 'United States' },
  { name: 'Chula Vista', country: 'United States' },
  { name: 'Durham', country: 'United States' },
  { name: 'Norfolk', country: 'United States' },
  { name: 'Garland', country: 'United States' },
  { name: 'Madison', country: 'United States' },
  { name: 'Hialeah', country: 'United States' },
  { name: 'Lubbock', country: 'United States' },
  { name: 'Reno', country: 'United States' },
  { name: 'Glendale', country: 'United States' },
  { name: 'Baton Rouge', country: 'United States' },
  { name: 'Irvine', country: 'United States' },
  { name: 'Chesapeake', country: 'United States' },
  { name: 'Irving', country: 'United States' },
  { name: 'Scottsdale', country: 'United States' },
  { name: 'North Las Vegas', country: 'United States' },
  { name: 'Fremont', country: 'United States' },
  { name: 'Gilbert', country: 'United States' },
  { name: 'San Bernardino', country: 'United States' },
  { name: 'Boise', country: 'United States' },
  { name: 'Birmingham', country: 'United States' },
];

export const IKIGAI_SUGGESTIONS = {
  whatYouLove: [
    'Рассмешивать людей',
    'Решать сложные задачи',
    'Создавать искусство',
    'Помогать другим быть услышанными',
    'Заботиться о животных',
    'Учить и делиться знаниями',
    'Исследовать природу',
    'Писать истории',
    'Играть музыку',
    'Готовить и экспериментировать',
  ],
  whatYouGoodAt: [
    'Слушать и понимать других',
    'Организовывать и планировать',
    'Творчески решать проблемы',
    'Ясно доносить мысли',
    'Выстраивать отношения',
    'Анализировать данные',
    'Обучать и объяснять',
    'Проектировать и создавать',
    'Вести команды',
    'Адаптироваться к изменениям',
  ],
  whatWorldNeeds: [
    'Больше эмпатии и понимания',
    'Экологическую устойчивость',
    'Поддержку ментального здоровья',
    'Доступ к обучению и развитию',
    'Доступное здравоохранение',
    'Связь и поддержку в сообществах',
    'Инновации и технологии',
    'Творческое самовыражение',
    'Социальную справедливость',
    'Экономическое равенство',
  ],
  whatCanBePaidFor: [
    'Консультационные услуги',
    'Креативный дизайн',
    'Коучинг и наставничество',
    'Писательство и создание контента',
    'Обучение и тренинги',
    'Техническая разработка',
    'Медицинские услуги',
    'Бизнес-стратегия',
    'Организация мероприятий',
    'Разработка продуктов',
  ],
};

export const IKIGAI_HELPERS = {
  whatYouLove: 'Какие занятия заставляют тебя терять счет времени и приносят настоящую радость.',
  whatYouGoodAt: 'Какие навыки даются тебе естественно и за что тебя чаще всего хвалят.',
  whatWorldNeeds: 'Какую проблему ты хочешь решить и какое влияние хочешь оказать на других.',
  whatCanBePaidFor: 'Какие навыки или услуги могут приносить доход? Мечтай по-крупному!',
};

export const getLifeContextQuestions = (t: (key: string) => string) => [
  {
    id: 'situation',
    question: t('onboarding.currentSituationQuestion').toUpperCase(),
    type: 'single',
    icon: 'person-pin',
    color: '#cdbad8',
    options: [
      { id: 'student', label: t('onboarding.situationOption1') },
      { id: 'early_career', label: t('onboarding.situationOption2') },
      { id: 'mid_career', label: t('onboarding.situationOption3') },
      { id: 'between', label: t('onboarding.situationOption4') },
      { id: 'building', label: t('onboarding.situationOption5') },
      { id: 'retired', label: t('onboarding.situationOption6') },
    ],
    storageKey: 'lifeContextSituation',
  },
  {
    id: 'constraint',
    question: t('onboarding.biggestConstraintQuestion').toUpperCase(),
    type: 'single',
    icon: 'block',
    color: '#bfacca',
    options: [
      { id: 'time', label: t('onboarding.constraintOption1') },
      { id: 'money', label: t('onboarding.constraintOption2') },
      { id: 'skills', label: t('onboarding.constraintOption3') },
      { id: 'confidence', label: t('onboarding.constraintOption4') },
      { id: 'clarity', label: t('onboarding.constraintOption5') },
    ],
    storageKey: 'lifeContextConstraint',
  },
  {
    id: 'matters',
    question: t('onboarding.whatMattersQuestion').toUpperCase(),
    subtitle: t('onboarding.selectUpToThree', { defaultValue: 'Select up to 3' }),
    type: 'multi',
    maxSelections: 3,
    icon: 'stars',
    color: '#baccd7',
    options: [
      { id: 'financial', label: t('onboarding.mattersOption1') },
      { id: 'creative', label: t('onboarding.mattersOption2') },
      { id: 'helping', label: t('onboarding.mattersOption3') },
      { id: 'flexibility', label: t('onboarding.mattersOption4') },
      { id: 'impact', label: t('onboarding.mattersOption5') },
      { id: 'learning', label: t('onboarding.mattersOption6') },
      { id: 'balance', label: t('onboarding.mattersOption7') },
      { id: 'recognition', label: t('onboarding.mattersOption8') },
    ],
    storageKey: 'lifeContextMatters',
  },
];

export const getOnboardingSteps = (t: (key: string) => string) => [
  { 
    id: 1, 
    title: t('onboarding.step1Title'), 
    content: t('onboarding.step1Content'),
    showImage: true,
    isForm: false,
  },
  { 
    id: 2, 
    title: t('onboarding.step2Title'), 
    content: '',
    showImage: false,
    isForm: true,
  },
  { 
    id: 3, 
    title: t('onboarding.step3Title'), 
    content: '',
    showImage: false,
    isForm: false,
    isPledge: true,
  },
  { 
    id: 4, 
    title: t('onboarding.step4Title'), 
    content: '',
    showImage: false,
    isForm: false,
    isIkigai: true,
  },
  { 
    id: 5, 
    title: t('onboarding.step5Title'), 
    content: '',
    showImage: false,
    isForm: false,
    isLifeContext: true,
  },
  { 
    id: 6, 
    title: t('onboarding.step6Title'), 
    content: '',
    showImage: false,
    isForm: false,
    isLoading: true,
  },
  { 
    id: 7, 
    title: t('onboarding.step7Title'), 
    content: '',
    showImage: false,
    isForm: false,
    isCallingAwaits: true,
  },
  { 
    id: 8, 
    title: t('onboarding.step8Title'), 
    content: '',
    showImage: false,
    isForm: false,
    isPathsAligned: true,
  },
  { 
    id: 9, 
    title: t('onboarding.step9Title'), 
    content: '',
    showImage: false,
    isForm: false,
    isForgeYourOwnPath: true,
  },
];
