export {
  APP_NARROW_WIDTH as ONBOARDING_NARROW_WIDTH,
  ONBOARDING_QUESTION_HEADER,
  ONBOARDING_QUESTION_OPTION,
  ONBOARDING_QUESTION_OPTION_TEXT,
  ONBOARDING_QUESTION_SUBTITLE,
  ONBOARDING_QUESTION_OPTIONS_GAP,
  isNarrowWidth as isOnboardingNarrowWidth,
} from '@/constants/typography';
