import { BodyStyle, ButtonHeadingStyle, HeadingStyle } from '@/constants/theme';
import { Platform, StyleSheet } from 'react-native';
import { height, width } from './constants';

// On iPad, _layout.tsx constrains content to 74% of window width.
// Use the same ratio so the cake image scales to the actual column, not the full window.
const cakeImageSize = Platform.isPad ? Math.round(width * 0.74 * 0.6885) : width * 0.6885;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  pathExplorationContainer: {
    flex: 1,
    position: 'relative',
    backgroundColor: 'transparent',
  },
  whiteZoomOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    width: width,
    height: height,
    zIndex: 9999,
    transformOrigin: 'center',
  },
  header: {
    flexDirection: 'row',
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1100,
    opacity: 1,
    elevation: 11,
    shadowColor: '#342846',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  backButtonText: {
    fontSize: 24,
    color: '#342846',
    fontWeight: 'bold',
  },
  headerSpacer: {
    flex: 1,
  },
  headerProgressContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  headerProgressBar: {
    width: '100%',
    height: 4,
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
    overflow: 'hidden',
  },
  headerProgressFill: {
    height: '100%',
    backgroundColor: '#342846',
    borderRadius: 2,
  },
  slider: {
    flexDirection: 'row',
    flex: 1,
  },
  stepContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 0, // Container padding handled by stepContent
    position: 'relative',
    overflow: 'hidden',
  },
  stepContent: {
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingTop: 40,
    paddingBottom: 120,
    width: '100%',
  },
  stepTitle: {
    ...HeadingStyle,
    color: '#342846',
    marginTop: -10,
    marginBottom: 16,
    textAlign: 'center',
    paddingHorizontal: 0, // Padding handled by stepContent parent
  },
  stepText: {
    ...BodyStyle,
    color: '#342846',
    textAlign: 'center',
    lineHeight: 26,
    marginBottom: 24,
    paddingHorizontal: 0, // Padding handled by stepContent parent
    width: '100%',
  },
  stepImage: {
    width: width * 0.7 * 1.35, // Increased by 35% (from 0.7 to 0.945)
    height: width * 0.7 * 1.35, // Increased by 35% (from 0.7 to 0.945)
    marginTop: 20,
    marginBottom: 20,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 24,
    paddingHorizontal: 40,
    paddingBottom: 40,
    zIndex: 1000,
    backgroundColor: 'transparent',
  },
  continueButton: {
    backgroundColor: '#342846',
    borderRadius: 999,
    paddingVertical: 16,
    paddingHorizontal: 40,
    alignItems: 'center',
    width: '100%',
  },
  continueButtonText: {
    ...ButtonHeadingStyle,
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  formContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
    position: 'relative',
    zIndex: 1,
  },
  formContainerScrollView: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  customPathFormBackgroundImage: {
    resizeMode: 'cover',
  },
  formContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 120,
    flexGrow: 1,
  },
  ikigaiFormContent: {
    paddingHorizontal: 40,
    paddingRight: 40,
    paddingLeft: 40,
    paddingTop: 120,
    paddingBottom: 200, // Increased padding to ensure last field stays above keyboard
    minHeight: '100%',
  },
  // Removed old ikigaiHorizontalScroll, ikigaiHorizontalContent, ikigaiCardContainer styles - now using FlatList
  ikigaiPagination: {
    position: 'absolute',
    bottom: 40,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    zIndex: 10,
  },
  ikigaiPaginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#D0D0D0',
  },
  ikigaiPaginationDotActive: {
    backgroundColor: '#342846',
    width: 24,
  },
  pathForwardFormContent: {
    paddingHorizontal: 40,
    paddingTop: 0,
    paddingBottom: 20,
    minHeight: '100%',
    justifyContent: 'center',
  },
  pathForwardTitleContainer: {
    paddingTop: 0,
    paddingHorizontal: 25,
    alignItems: 'center',
  },
  pathForwardTitle: {
    marginBottom: 20,
  },
  pathForwardScrollView: {
    flex: 1,
    width: '100%',
  },
  pathForwardContent: {
    paddingLeft: 40,
    paddingRight: 40,
    paddingTop: 40,
    paddingBottom: 80,
    width: '100%',
  },
  pathForwardQuestionContainer: {
    marginBottom: 20,
    width: '100%',
    alignSelf: 'stretch',
  },
  pathForwardHorizontalScroll: {
    flex: 1,
  },
  pathForwardHorizontalContent: {
    flexDirection: 'row',
  },
  pathForwardCardContainer: {
    width: width,
    flex: 1,
    paddingHorizontal: 40,
    paddingTop: 20,
    paddingBottom: 20,
    justifyContent: 'center',
  },
  pathForwardFieldContainer: {
    marginBottom: 0,
    marginTop: -50,
    position: 'relative',
    alignItems: 'flex-start',
    paddingTop: 20,
    paddingHorizontal: 40,
    paddingBottom: 20,
    overflow: 'visible',
    width: '100%',
    flex: 1,
    justifyContent: 'center',
  },
  pathForwardPagination: {
    position: 'absolute',
    top: 75,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    zIndex: 10,
  },
  pathForwardPaginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#D0D0D0',
  },
  pathForwardPaginationDotActive: {
    backgroundColor: '#342846',
    width: 24,
  },
  pathForwardContinueButton: {
    alignItems: 'center',
    backgroundColor: '#342846',
    borderRadius: 999,
    paddingVertical: 16,
    paddingHorizontal: 40,
    alignSelf: 'center',
    minWidth: 200,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    marginHorizontal: 20,
    marginBottom: 40,
    zIndex: 1000,
  },
  pathForwardContinueButtonText: {
    ...ButtonHeadingStyle,
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  pathForwardFieldLabel: {
    ...HeadingStyle,
    color: '#342846',
    marginBottom: 12,
    fontSize: 18,
    textAlign: 'center',
    width: '100%',
    minHeight: 24,
    backgroundColor: 'transparent',
  },
  pathForwardFieldBodyText: {
    ...BodyStyle,
    color: '#342846',
    marginBottom: 10,
    fontSize: 14,
    width: '100%',
    textAlign: 'center',
    opacity: 0.8,
    lineHeight: 20,
    paddingHorizontal: 45,
    backgroundColor: 'transparent',
  },
  // New Ikigai Form Styles
  ikigaiFormContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  ikigaiScrollView: {
    flex: 1,
  },
  ikigaiScrollContent: {
    flexGrow: 1,
    paddingBottom: 120, // Increased to accommodate absolutely positioned bottom nav
  },
  ikigaiLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F9F7F4',
  },
  ikigaiLoadingText: {
    fontSize: 16,
    color: '#666',
  },
  ikigaiHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: 'transparent',
  },
  ikigaiHeaderButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#342846',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ikigaiProgressBarContainer: {
    flex: 1,
    marginHorizontal: 20,
  },
  ikigaiProgressBarBg: {
    height: 4,
    backgroundColor: 'rgba(52, 40, 70, 0.1)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  ikigaiProgressBarFill: {
    height: '100%',
    borderRadius: 2,
  },
  ikigaiTitleSection: {
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 10,
    marginTop: 10,
  },
  ikigaiMainTitle: {
    ...HeadingStyle,
    fontSize: 24,
    lineHeight: 28,
    color: '#342846',
    textAlign: 'center',
  },
  ikigaiVisualArea: {
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 10,
  },
  ikigaiVisualSwitcher: {
    width: width,
    height: 150,
    position: 'relative',
  },
  ikigaiVisualItem: {
    position: 'absolute',
    width: width,
    height: 150,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ikigaiVisualContainer: {
    width: 100,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  ikigaiMainIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  ikigaiFloatingHeart: {
    position: 'absolute',
  },
  ikigaiTwinkleStar: {
    position: 'absolute',
  },
  ikigaiShineOverlay: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#FFFFFF',
  },
  ikigaiFloatingCoin: {
    position: 'absolute',
  },
  ikigaiGlowCircle: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  ikigaiRipple: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
  },
  ikigaiStepIndicator: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    gap: 8,
  },
  ikigaiStepDot: {
    height: 8,
    borderRadius: 4,
  },
  ikigaiCarouselContainer: {
    minHeight: 400,
    marginBottom: 10,
  },
  ikigaiCardWrapper: {
    width: width,
    paddingHorizontal: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ikigaiQuestionCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.46)',
    borderRadius: 20,
    padding: 20,
    width: width - 40,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    marginVertical: 10,
  },
  ikigaiIconBadge: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    alignSelf: 'center',
  },
  ikigaiIconImage: {
    width: 28,
    height: 28,
  },
  ikigaiQuestionText: {
    ...HeadingStyle,
    fontSize: 20,
    color: '#342846',
    textAlign: 'center',
    marginBottom: 12,
  },
  ikigaiDescriptionText: {
    ...BodyStyle,
    fontSize: 14,
    lineHeight: 20,
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
  },
  ikigaiInputContainer: {
    borderWidth: 2,
    borderRadius: 14,
    backgroundColor: '#FAFAFA',
    overflow: 'hidden',
    marginBottom: 12,
  },
  ikigaiTextInput: {
    ...BodyStyle,
    fontSize: 15,
    lineHeight: 18, // Reduced lineHeight to match fontSize more closely (was 22)
    color: '#342846',
    paddingTop: 10, // Increased by 4px to move text down
    paddingBottom: 14, // Decreased by 4px to maintain spacing
    paddingHorizontal: 16,
    minHeight: 120,
    textAlignVertical: 'top', // Ensure text starts at top for multiline
    includeFontPadding: false, // Prevent extra padding on Android
  },
  ikigaiCharHint: {
    ...BodyStyle,
    fontSize: 12,
    color: '#999',
    textAlign: 'right',
  },
  ikigaiBottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    paddingHorizontal: 40,
    paddingBottom: 40,
    backgroundColor: 'transparent',
    gap: 12,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  ikigaiBackButtonNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 25,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#342846',
    gap: 8,
    minHeight: 50,
  },
  ikigaiBackButtonText: {
    ...BodyStyle,
    fontSize: 16,
    color: '#342846',
    fontWeight: '600',
    lineHeight: 20,
  },
  ikigaiNextButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingLeft: 24,
    paddingRight: 24,
    borderRadius: 999,
    flex: 1,
    minHeight: 50,
  },
  ikigaiNextButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  ikigaiNextButtonText: {
    ...ButtonHeadingStyle,
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
    lineHeight: 20,
    textAlign: 'center',
    flexShrink: 1,
  },
  ikigaiNextButtonIcon: {
    flexShrink: 0,
  },
  ikigaiProgressWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    marginTop: -60,
    width: '100%',
  },
  ikigaiProgressLine: {
    width: 24,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: '#D0D0D0',
    marginHorizontal: 4,
  },
  ikigaiProgressLineActive: {
    backgroundColor: '#342846',
  },
  ikigaiProgressCounterContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginLeft: 12,
  },
  ikigaiNavigationButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 25,
    paddingRight: 25,
    paddingBottom: 40,
    paddingTop: 10,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'transparent',
    gap: 0,
    zIndex: 5,
    pointerEvents: 'box-none',
  },
  ikigaiNavigationButtonsCentered: {
    justifyContent: 'center',
  },
  ikigaiNavButtonCentered: {
    alignSelf: 'center',
  },
  ikigaiNavButton: {
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 999,
    backgroundColor: '#342846',
    minWidth: 200,
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'auto',
  },
  ikigaiNavButtonLeft: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    paddingLeft: 28,
    paddingRight: 28,
    minWidth: 140,
    marginLeft: 0,
  },
  ikigaiNavButtonRight: {
    paddingRight: 40,
    marginRight: 0,
  },
  ikigaiContinueButton: {
    minWidth: 200,
  },
  ikigaiNavButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  ikigaiNavButtonIcon: {
    marginRight: 0,
  },
  ikigaiNavButtonText: {
    ...ButtonHeadingStyle,
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
  },
  ikigaiNavButtonTextLeft: {
    ...ButtonHeadingStyle,
    color: '#342846',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
  },
  ikigaiLastQuestionBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
    paddingVertical: 20,
    paddingHorizontal: 48,
    borderRadius: 999,
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#342846',
  },
  ikigaiLastQuestionBackButtonText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 20,
    marginLeft: 8,
    fontWeight: '600',
  },
  ikigaiTitleContainer: {
    alignItems: 'center',
    marginBottom: 30,
  },
  formTitle: {
    ...HeadingStyle,
    color: '#342846',
    textAlign: 'center',
    marginTop: 0,
    marginBottom: 55,
    lineHeight: 25,
  },
  ikigaiTitleLine1: {
    marginBottom: 10,
  },
  aboutYouTitle: {
    ...HeadingStyle,
    color: '#342846',
    textAlign: 'center',
    marginTop: 0,
    marginBottom: 30,
    lineHeight: 32,
  },
  ikigaiHelpButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1100,
    opacity: 1,
    elevation: 11,
    shadowColor: '#342846',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  headerTooltipContainer: {
    position: 'absolute',
    top: 108,
    right: 20,
    zIndex: 1400,
    elevation: 1400,
    maxWidth: 230,
  },
  headerTooltipBubble: {
    backgroundColor: 'rgba(52, 40, 70, 0.95)',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  headerTooltipText: {
    ...BodyStyle,
    color: '#FFFFFF',
    fontSize: 12,
    lineHeight: 16,
  },
  ikigaiModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  ikigaiModalWrapper: {
    alignItems: 'center',
    width: '100%',
    maxWidth: 400,
  },
  ikigaiModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 32,
    paddingTop: 56,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 10,
  },
  ikigaiModalIcon: {
    width: 74,
    height: 74,
    zIndex: 1,
    marginBottom: -37,
  },
  ikigaiModalFallbackIconCircle: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: '#342846',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    marginBottom: -37,
  },
  ikigaiModalTitle: {
    ...HeadingStyle,
    fontSize: 24,
    color: '#342846',
    textAlign: 'center',
    marginBottom: 16,
  },
  ikigaiModalText: {
    ...BodyStyle,
    fontSize: 16,
    color: '#342846',
    textAlign: 'center',
    marginBottom: 24,
  },
  ikigaiModalBold: {
    fontWeight: '700',
    color: '#342846',
  },
  ikigaiModalButton: {
    backgroundColor: '#342846',
    paddingVertical: 16,
    borderRadius: 999,
    alignItems: 'center',
  },
  ikigaiModalButtonText: {
    ...BodyStyle,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  formBodyText: {
    ...BodyStyle,
    color: '#342846',
    textAlign: 'center',
    marginTop: -20,
    marginBottom: 32,
    paddingTop: 0,
    lineHeight: 20,
    paddingHorizontal: 40,
  },
  formBodyTextRussian: {
    // Removed special positioning - fields now at original height
  },
  fieldContainer: {
    marginBottom: 24,
    position: 'relative',
    alignItems: 'center', // Center answer fields horizontally
    width: '100%', // Full width for centering
    backgroundColor: 'transparent',
    minHeight: 100,
  },
  ikigaiFieldContainer: {
    marginBottom: 0,
    position: 'relative',
    alignItems: 'center', // Center answer fields horizontally
    paddingTop: 135,
    paddingHorizontal: 40,
    paddingBottom: 20,
    overflow: 'visible', // Ensure stars aren't clipped
    width: '100%', // Full width for centering
    flex: 1,
    justifyContent: 'flex-start',
    alignSelf: 'stretch',
  },
  ikigaiFieldContainerRed: {
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 10,
  },
  ikigaiFieldContainerPurple: {
    shadowColor: '#9B59B6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 10,
  },
  ikigaiFieldContainerGreen: {
    shadowColor: '#52C41A',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 10,
  },
  ikigaiFieldContainerGold: {
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 10,
  },
  // New clean card styles
  ikigaiSectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
    width: '100%',
  },
  ikigaiSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  ikigaiSectionIcon: {
    width: 24,
    height: 24,
  },
  ikigaiSectionHeaderText: {
    flex: 1,
  },
  ikigaiSectionTitle: {
    ...HeadingStyle,
    fontSize: 16,
    color: '#342846',
  },
  ikigaiSectionDescription: {
    ...BodyStyle,
    fontSize: 14,
    lineHeight: 20,
    color: '#666',
    marginBottom: 16,
  },
  ikigaiCharCount: {
    ...BodyStyle,
    fontSize: 12,
    color: '#999',
    textAlign: 'right',
    marginTop: 8,
  },
  questionCounter: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 12,
    marginBottom: 6,
    marginTop: -10,
    textAlign: 'center',
    opacity: 0.7,
    width: '100%',
  },
  dreamQuestionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 16,
    width: '100%',
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  dreamIcon: {
    width: 60,
    height: 60,
    marginRight: 12,
  },
  fieldLabel: {
    ...HeadingStyle,
    color: '#342846',
    marginTop: 0,
    marginBottom: 15,
    fontSize: 18,
    textAlign: 'center',
  },
  fieldLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  helperIcon: {
    marginLeft: 8,
    marginBottom: 15,
    padding: 4,
  },
  tooltipOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  tooltipContainer: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    overflow: 'visible',
    position: 'relative',
    width: '100%',
    maxWidth: 300,
    minHeight: 150,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#342846',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  tooltipTextContainer: {
    minHeight: 0,
  },
  tooltipText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
    lineHeight: 19.2,
    textAlign: 'center',
    textAlignVertical: 'center',
    width: '100%',
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  tooltipCloseButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    padding: 4,
    zIndex: 10,
  },
  ikigaiFieldLabel: {
    ...HeadingStyle,
    color: '#342846',
    marginTop: -165,
    marginBottom: 45,
    fontSize: 20,
    textAlign: 'center',
    width: '100%',
  },
  fieldBodyTextContainer: {
    width: '130%',
    alignSelf: 'center',
    marginTop: -5,
    marginBottom: 20,
  },
  fieldBodyText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    width: '100%',
    textAlign: 'center',
    opacity: 0.7,
    lineHeight: 20,
  },
  textFieldWrapper: {
    backgroundColor: '#FFFFFF',
    borderWidth: 0,
    borderRadius: 8,
    overflow: 'visible', // Changed to visible to allow shadow to show
    position: 'relative',
    width: '100%', // Full width for centering
    justifyContent: 'center', // Center content vertically
    // Subtle brown shadow
    shadowColor: '#342846',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8, // For Android
  },
  bodyTextFieldWrapper: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    overflow: 'visible', // Changed to visible to allow shadow to show
    position: 'relative',
    width: '100%', // Full width
    minHeight: 90, // Reduced height for more compact layout
    marginTop: 8, // Reduced spacing between body text and answer field
    alignSelf: 'flex-start', // Align to left
    // Purple 3D shadow
    shadowColor: '#342846',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.6,
    shadowRadius: 16,
    elevation: 12, // For Android
    zIndex: 1, // Ensure it's above other elements
  },
  nameFieldWrapper: {
    maxWidth: 300, // Narrower width for name field
    alignSelf: 'center', // Center the narrower field
  },
  ikigaiTextFieldWrapper: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    overflow: 'visible', // Changed to visible to allow shadow to show
    position: 'relative',
    minHeight: 130, // Increased by 30% from 100 (100 * 1.3 = 130)
    width: '100%', // Ensure full width for centering
    maxWidth: 300,
    alignSelf: 'center',
    marginTop: 30,
    zIndex: 10,
    // Subtle brown shadow
    shadowColor: '#342846',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8, // For Android
  },
  cityFieldWrapper: {
    position: 'relative',
    width: '100%',
    maxWidth: 300, // Same width as name field
    alignSelf: 'center', // Center the field
  },
  textField: {
    ...BodyStyle,
    paddingHorizontal: 20, // Minimum 20px padding (was 16)
    paddingTop: 8, // Increased by 4px to move text down
    paddingBottom: 12, // Decreased by 4px to maintain spacing
    color: '#342846',
    fontSize: 14, // Reduced by 2px from 16 (affects placeholder helper text)
    lineHeight: 16, // Reduced lineHeight to match fontSize more closely (was 20)
    flexWrap: 'wrap',
    textAlign: 'center', // Center align text horizontally
    textAlignVertical: 'center', // Center align text vertically
    width: '100%', // Full width
    includeFontPadding: false, // Prevent extra padding on Android
  },
  dateRow: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center', // Center date fields
    width: '100%',
  },
  dateField: {
    width: 70, // Narrower width for 2-digit fields (MM, DD)
  },
  dateFieldYear: {
    width: 90, // Narrower width for 4-digit year field (YYYY)
  },
  timeRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    justifyContent: 'center', // Center time fields
    width: '100%',
  },
  timeRowRussian: {
    justifyContent: 'center', // Center the time fields for Russian version (no AM/PM)
  },
  timeField: {
    width: 70, // Narrower width for 2-digit fields (HH, MM)
  },
  amPmField: {
    width: 80,
    position: 'relative',
    zIndex: 100,
    overflow: 'visible', // Override textFieldWrapper's overflow: 'hidden'
  },
  dropdownButtonWrapper: {
    width: '100%',
  },
  dropdownGradient: {
    width: '100%',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  dropdownButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    width: '100%',
  },
  dropdownText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
  },
  dropdownArrow: {
    fontSize: 10,
    color: '#342846',
  },
  dropdownMenu: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    marginTop: 4,
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  dropdownMenuUp: {
    position: 'absolute',
    bottom: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    marginBottom: 4,
    zIndex: 1001,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 10,
    minHeight: 44,
  },
  dropdownItem: {
    paddingHorizontal: 20, // Minimum 20px padding (was 16)
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
  },
  dropdownItemText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
  },
  checkboxContainer: {
    marginBottom: 24,
    alignItems: 'center', // Center checkbox
    width: '100%',
  },
  checkbox: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkboxBox: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 4,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  checkboxChecked: {
    backgroundColor: '#342846',
  },
  checkmark: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  checkboxLabel: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
  },
  cityDropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    marginTop: 4,
    zIndex: 1000,
    maxHeight: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
    overflow: 'hidden',
  },
  cityDropdownScrollView: {
    maxHeight: 200,
  },
  citySearchingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 10,
  },
  citySearchingText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 13,
    opacity: 0.7,
  },
  cityDropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
  },
  cityDropdownContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cityDropdownText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    fontWeight: '500',
  },
  cityDropdownCountry: {
    ...BodyStyle,
    color: '#999',
    fontSize: 14,
  },
  hintText: {
    ...BodyStyle,
    fontSize: 12,
    color: '#342846',
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 14.4, // Reduced by 20% (from 18 to 14.4)
  },
  imageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5.6, // Reduced by 30% from 8
    marginBottom: 20,
  },
  cakeImage: {
    width: cakeImageSize,
    height: cakeImageSize,
  },
  pledgeContainer: {
    flex: 1,
    width: '100%',
  },
  pledgeContentContainer: {
    paddingHorizontal: 30,
    paddingTop: 25,
    paddingBottom: 40,
  },
  pledgeTitle: {
    ...HeadingStyle,
    color: '#342846',
    marginTop: 0,
    marginBottom: 32,
    textAlign: 'center',
  },
  pledgeContent: {
    width: '100%',
    maxWidth: width - 60, // 30px padding on each side
    alignSelf: 'center',
    alignItems: 'center',
  },
  pledgeText: {
    ...BodyStyle,
    color: '#342846',
    textAlign: 'center',
    lineHeight: 26,
    marginBottom: 32,
    fontSize: 16,
  },
  pledgeName: {
    fontFamily: 'AnonymousPro-Regular',
  },
  pledgeSubtext: {
    ...BodyStyle,
    color: '#342846',
    textAlign: 'center',
    lineHeight: 24,
    fontSize: 16,
  },
  signatureContainer: {
    marginTop: 40,
    width: '100%',
    alignItems: 'center',
  },
  signatureLabel: {
    ...BodyStyle,
    color: '#342846',
    marginBottom: 12,
    fontSize: 16,
    textAlign: 'center',
  },
  signatureWrapper: {
    width: '100%',
    maxWidth: 495, // Expanded by 25% then additional 10% then additional 20% (300 * 1.25 * 1.1 * 1.2)
    alignSelf: 'center',
    height: 212.5, // Expanded by 25% (170 * 1.25)
    borderWidth: 0,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  clearSignatureButton: {
    marginTop: 12,
    paddingVertical: 8,
    paddingHorizontal: 20, // Minimum 20px padding (was 16)
    borderRadius: 6,
    backgroundColor: '#f0f0f0',
  },
  clearSignatureText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
  },
  pledgeTextFieldWrapper: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    marginTop: 32,
    width: '100%',
    overflow: 'visible', // Changed to visible to allow shadow to show
    minHeight: 100,
    // Subtle brown shadow
    shadowColor: '#342846',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8, // For Android
  },
  pledgeTextFieldContainer: {
    minHeight: 100,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  pledgeTextField: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    textAlign: 'left',
    width: '100%',
    padding: 0,
    margin: 0,
    textAlignVertical: 'center', // Center align text vertically
    includeFontPadding: false, // Prevent extra padding on Android
  },
  dontKnowTimeModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 25,
  },
  dontKnowTimeModal: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    position: 'relative',
  },
  dontKnowTimeModalCloseButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    padding: 4,
    zIndex: 10,
  },
  dontKnowTimeModalCloseX: {
    fontSize: 16,
    color: '#342846',
    fontWeight: 'bold',
  },
  dontKnowTimeModalTitle: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 24,
    lineHeight: 24,
  },
  dontKnowTimeModalConfirmButton: {
    backgroundColor: '#342846',
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  dontKnowTimeModalConfirmButtonText: {
    ...BodyStyle,
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  starButton: {
    position: 'absolute',
    top: 8,
    left: 8,
    zIndex: 100,
    padding: 4,
    backgroundColor: 'transparent',
  },
  starButtonOutside: {
    position: 'absolute',
    top: 0, // Align with top of field container
    right: -20, // Position outside container, accounting for star size and padding
    zIndex: 100,
    padding: 10, // Generous padding for touch target and visibility
    backgroundColor: 'transparent',
  },
  starButtonLeft: {
    position: 'absolute',
    top: '50%', // Center vertically
    left: -20, // Position outside container on the left side
    zIndex: 100,
    padding: 0, // No padding
    backgroundColor: 'transparent',
    transform: [{ translateY: 12.2 }], // Moved down by 15px more from -2.8
  },
  emojiButtonContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 35,
    marginBottom: 8,
    width: '100%',
  },
  starButtonCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 4,
    backgroundColor: 'transparent',
  },
  emojiWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  clickText: {
    fontSize: 10,
    color: '#342846',
    textAlign: 'center',
    marginTop: 5,
    marginBottom: -30,
    fontWeight: '600',
  },
  starContainer: {
    width: 40,
    height: 40,
    borderRadius: 20, // Make it circular
    backgroundColor: '#FFFFFF',
    borderWidth: 0.5,
    borderColor: '#342846',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4, // Add padding around the emoji
  },
  starIcon: {
    fontSize: 17.92,
  },
  starIconImage: {
    width: 49,
    height: 49,
  },
  assistanceButton: {
    marginTop: 8,
    alignSelf: 'flex-start', // Align to the left, same as field and question
  },
  assistanceText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
    textAlign: 'center', // Center align text
    marginBottom: 1.4, // 10% of fontSize (14 * 0.1 = 1.4)
  },
  star: {
    color: '#342846',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    maxHeight: '70%',
  },
  modalTitle: {
    ...HeadingStyle,
    color: '#342846',
    marginBottom: 12,
    textAlign: 'center',
  },
  modalHelperText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
    marginBottom: 20,
    textAlign: 'center',
    paddingHorizontal: 20, // Minimum 20px padding (was 16)
    lineHeight: 20,
  },
  suggestionsList: {
    maxHeight: 300,
    marginBottom: 20,
  },
  suggestionItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
  },
  suggestionText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
  },
  modalCloseButton: {
    backgroundColor: '#342846',
    borderRadius: 999,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  modalCloseText: {
    ...BodyStyle,
    color: '#fff',
    fontSize: 16,
  },
  loadingContainer: {
    flex: 1,
    width: '100%',
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 40,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  loadingTitle: {
    ...HeadingStyle,
    color: '#342846',
    marginBottom: 20,
    marginTop: -10,
    textAlign: 'center',
  },
  loadingTitleRussian: {
    marginBottom: 20,
  },
  deerFaceImage: {
    width: width * 0.5,
    height: width * 0.5,
    marginBottom: 40,
  },
  loadingList: {
    width: '100%',
    alignItems: 'center', // Center the list items
  },
  loadingItem: {
    marginBottom: 16,
    alignItems: 'center', // Center each item
  },
  loadingItemText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    textAlign: 'center', // Center the text
  },
  journeyLoadingContainer: {
    flex: 1,
    width: '100%',
    paddingTop: 0,
    paddingBottom: 40,
    paddingHorizontal: 40,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  journeyLoadingTitle: {
    ...HeadingStyle,
    color: '#342846',
    marginBottom: 40,
    textAlign: 'center',
    textTransform: 'none',
  },
  journeyDeerImage: {
    width: Platform.isPad ? Math.round(width * 0.74 * 0.35) : width * 0.5,
    height: Platform.isPad ? Math.round(width * 0.74 * 0.35) : width * 0.5,
    marginBottom: 40,
  },
  journeyLoadingList: {
    width: '100%',
    alignItems: 'center',
  },
  journeyLoadingItem: {
    marginBottom: 12,
  },
  journeyLoadingItemText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 18,
    textAlign: 'center',
  },
  destinyContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
    minHeight: '100%',
  },
  destinyTopSection: {
    alignItems: 'center',
    marginBottom: 20,
    paddingTop: 0,
  },
  userIconContainer: {
    marginBottom: 16,
  },
  userIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#342846',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#342846',
  },
  userIconText: {
    ...HeadingStyle,
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
  },
  destinyNameText: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 28,
    marginBottom: 8,
    textAlign: 'center',
  },
  destinyTitleText: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 20,
    textAlign: 'center',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 0,
    marginBottom: 24,
    width: '100%',
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#342846',
  },
  dividerText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 12,
    marginHorizontal: 12,
    textTransform: 'lowercase',
  },
  giftsContainer: {
    marginBottom: 32,
    gap: 16,
  },
  giftCard: {
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: '#342846',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  giftCardImage: {
    borderRadius: 12,
  },
  giftCardHeading: {
    ...HeadingStyle,
    color: '#ffffff',
    fontSize: 18,
    marginBottom: 8,
    textAlign: 'center',
  },
  giftCardBody: {
    ...BodyStyle,
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  ikigaiMapSection: {
    alignItems: 'center',
    marginTop: 'auto',
    paddingTop: 20,
  },
  ikigaiMapTitle: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 12,
    marginBottom: 12,
    textAlign: 'center',
    textTransform: 'lowercase',
  },
  ikigaiPurposeText: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 24,
  },
  destinyContinueButton: {
    backgroundColor: '#bfacca',
    borderRadius: 999,
    paddingVertical: 16,
    paddingHorizontal: 40,
    minWidth: 200,
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    marginHorizontal: 20,
    marginBottom: 40,
    zIndex: 1000,
  },
  destinyContinueButtonText: {
    ...ButtonHeadingStyle,
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  ikigaiContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    marginTop: 20, // Add spacing from gifts list
    position: 'relative',
  },
  ikigaiAuraContainer: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 0,
  },
  ikigaiAuraLayer1: {
    position: 'absolute',
    width: width * 0.65, // Smaller size to not cover gifts list
    height: width * 0.65,
    borderRadius: (width * 0.65) / 2,
    overflow: 'hidden', // Ensure gradient respects border radius
  },
  ikigaiAuraLayer2: {
    position: 'absolute',
    width: width * 0.58,
    height: width * 0.58,
    borderRadius: (width * 0.58) / 2,
    overflow: 'hidden', // Ensure gradient respects border radius
  },
  ikigaiAuraLayer3: {
    position: 'absolute',
    width: width * 0.51,
    height: width * 0.51,
    borderRadius: (width * 0.51) / 2,
    overflow: 'hidden', // Ensure gradient respects border radius
  },
  ikigaiAuraLayer4: {
    position: 'absolute',
    width: width * 0.44,
    height: width * 0.44,
    borderRadius: (width * 0.44) / 2,
    overflow: 'hidden', // Ensure gradient respects border radius
  },
  ikigaiImageWrapper: {
    width: width * 0.8,
    height: width * 0.8,
    position: 'relative',
    zIndex: 1,
  },
  ikigaiImage: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  ikigaiCircleText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 11,
    textAlign: 'center',
    lineHeight: 14,
    paddingHorizontal: 20, // Minimum 20px padding (was 8)
  },
  ikigaiCircleTextTop: {
    position: 'absolute',
    top: width * 0.8 * 0.05, // 5% of image height
    left: width * 0.8 * 0.35, // Center horizontally (50% - 15% for half width)
    width: width * 0.3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ikigaiCircleTextRight: {
    position: 'absolute',
    top: width * 0.8 * 0.35, // Center vertically
    right: width * 0.8 * 0.05, // 5% from right
    width: width * 0.3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ikigaiCircleTextBottom: {
    position: 'absolute',
    bottom: width * 0.8 * 0.05, // 5% from bottom
    left: width * 0.8 * 0.35, // Center horizontally
    width: width * 0.3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ikigaiCircleTextLeft: {
    position: 'absolute',
    top: width * 0.8 * 0.35, // Center vertically
    left: width * 0.8 * 0.05, // 5% from left
    width: width * 0.3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ikigaiCenterCircleWrapper: {
    width: width * 0.6,
    height: width * 0.6,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  ikigaiCenterBackground: {
    backgroundColor: '#baccd7', // Match the pulsating circle background color
    borderRadius: (width * 0.6) / 2, // Make it a perfect circle
    width: width * 0.6,
    height: width * 0.6,
    paddingHorizontal: 20,
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ikigaiCenterSummary: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    fontWeight: 'bold',
    paddingHorizontal: 20, // Minimum 20px padding (was 10)
  },
  pathsContent: {
    paddingHorizontal: 40,
    paddingTop: 0,
    paddingBottom: 20,
    minHeight: '100%',
    alignItems: 'center',
  },
  pathsBodyText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
    textAlign: 'center',
    marginTop: -32,
    marginBottom: 24,
    paddingHorizontal: 0, // Padding handled by pathsContent parent (40px)
    lineHeight: 18,
  },
  pathCardContainer: {
    position: 'relative',
    marginBottom: 32,
    width: '100%',
    alignSelf: 'center',
  },
  pathCardGlow: {
    position: 'absolute',
    top: -8,
    left: -8,
    right: -8,
    bottom: -8,
    borderRadius: 12,
    opacity: 0.7,
  },
  pathCardGlowOverlay: {
    position: 'absolute',
    top: -8,
    left: -8,
    right: -8,
    bottom: -8,
    borderRadius: 12,
    opacity: 0.5,
  },
  pathCard: {
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    shadowColor: '#342846',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
    width: '100%',
    position: 'relative',
    zIndex: 1,
    overflow: 'hidden',
  },
  pathCardImage: {
    borderRadius: 8,
    resizeMode: 'stretch',
  },
  pathCardContent: {
    padding: 16,
  },
  loadingText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    textAlign: 'center',
  },
  pathTitle: {
    ...HeadingStyle,
    color: '#FFFFFF',
    fontSize: 20,
    marginBottom: 12,
    textAlign: 'center',
  },
  pathDescription: {
    ...BodyStyle,
    color: '#FFFFFF',
    fontSize: 16,
    marginBottom: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  exploreButton: {
    flexDirection: 'row',
    backgroundColor: '#342846',
    borderRadius: 999,
    paddingVertical: 13, // Increased by 5px from 8 (8 + 5 = 13)
    paddingHorizontal: 40,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    minWidth: 200,
    gap: 6,
  },
  exploreButtonText: {
    ...ButtonHeadingStyle,
    color: '#fff',
    fontSize: 15,
  },
  customPathWrapper: {
    marginTop: 20,
    marginBottom: 20,
    alignItems: 'center',
  },
  customPathContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  customPathIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#342846',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    marginLeft: -8,
  },
  customPathTextContainer: {
    alignItems: 'flex-start',
  },
  customPathHeading: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 16,
    textDecorationLine: 'underline',
    marginBottom: 4,
  },
  customPathBody: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
  },
  dreamGoalButtonWrapper: {
    marginTop: 20,
    marginBottom: 20,
  },
  dreamGoalButton: {
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#342846',
    minWidth: 200,
    minHeight: 50,
  },
  dreamGoalButtonText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 18,
    fontWeight: '400',
  },
  pathLoadingContainer: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 25,
    position: 'relative',
    zIndex: 1,
  },
  pathLoadingTitle: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 24,
    marginBottom: 40,
    textAlign: 'center',
    textTransform: 'lowercase',
  },
  deerButterflyImage: {
    width: width * 0.6,
    height: width * 0.6,
  },
  pathExplorationContent: {
    paddingHorizontal: 40,
    paddingTop: 20,
    paddingBottom: 20,
    minHeight: '100%',
  },
  pathNameTitle: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 32,
    marginBottom: 12,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  futureTrajectoryTitle: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    marginBottom: 32,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1,
    opacity: 0.7,
  },
  whyFitsYouCardContainer: {
    position: 'relative',
    marginBottom: 32,
    width: '100%',
    alignSelf: 'center',
  },
  whyFitsYouCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#342846',
    padding: 24,
    minHeight: 200,
    position: 'relative',
    zIndex: 1,
    overflow: 'hidden',
  },
  whyFitsYouCardImage: {
    borderRadius: 16,
    resizeMode: 'cover',
  },
  whyFitsYouHeader: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#FFFFFF',
  },
  whyFitsYouLabel: {
    ...BodyStyle,
    color: '#FFFFFF',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  whyFitsYouName: {
    ...HeadingStyle,
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
  },
  whyFitsYouBio: {
    gap: 16,
  },
  whyFitsYouBioText: {
    ...BodyStyle,
    color: '#FFFFFF',
    fontSize: 16,
    lineHeight: 24,
  },
  goalsSectionTitle: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 20,
    marginBottom: 20,
    textAlign: 'center',
  },
  goalCard: {
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    padding: 20,
    marginBottom: 20,
    backgroundColor: '#fff',
    width: '100%',
    alignSelf: 'center',
    overflow: 'visible', // Changed to visible to allow shadow to show
    // Subtle brown shadow
    shadowColor: '#342846',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8, // For Android
  },
  goalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  goalTitle: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 20,
    flex: 1,
    textAlign: 'left',
    marginRight: 12,
  },
  goalDescriptorBadge: {
    backgroundColor: 'rgba(52, 40, 70, 0.2)', // 20% opacity purple
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 20, // Minimum 20px padding (was 16)
  },
  goalDescriptorText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  goalTimeFrameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  goalTimeFrameIcon: {
    marginRight: 6,
  },
  goalTimeFrame: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 12,
    fontWeight: '400',
    textAlign: 'left',
  },
  goalDescription: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'left',
    marginBottom: 20,
  },
  startJourneyButton: {
    backgroundColor: '#342846',
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 999,
    paddingVertical: 12,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginTop: 8,
  },
  startJourneyButtonText: {
    ...BodyStyle,
    color: '#fff',
    fontSize: 16,
    fontWeight: '400',
    marginRight: 8,
  },
  startJourneyArrow: {
    marginLeft: 0,
  },
  paywallContent: {
    paddingHorizontal: 25,
    paddingTop: 20,
    paddingBottom: 200,
    minHeight: '100%',
    alignItems: 'center',
  },
  paywallTitle: {
    ...HeadingStyle,
    color: '#342846',
    marginTop: 0,
    marginBottom: 12,
    textAlign: 'center',
  },
  paywallSubtitle: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 18,
    marginTop: 20,
    marginBottom: 8,
    textAlign: 'center',
  },
  activeGoalContainer: {
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 24,
    marginTop: 16,
    marginBottom: 32,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    width: '100%',
    alignItems: 'center',
  },
  activeGoalSubheading: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
    marginTop: 0,
    marginBottom: 8,
    textAlign: 'center',
    opacity: 0.7,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  goalNameText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 18,
    marginBottom: 0,
    textAlign: 'center',
    fontWeight: '600',
  },
  goalTitleText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    marginBottom: 32,
    textAlign: 'center',
  },
  goalStepsContainer: {
    width: '100%',
    marginTop: 20,
    marginBottom: 40,
    alignItems: 'flex-start',
  },
  levelsContainer: {
    width: '100%',
    marginTop: 20,
    marginBottom: 40,
    alignItems: 'flex-start',
    position: 'relative',
  },
  continuousConnector: {
    position: 'absolute',
    left: 23,
    top: 24,
    width: 2,
    bottom: 0,
    backgroundColor: '#342846',
    zIndex: 0,
  },
  levelItem: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 24,
    alignItems: 'flex-start',
    position: 'relative',
    zIndex: 2,
  },
  levelBadgeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    position: 'relative',
    zIndex: 2,
    width: 48,
    height: 48,
  },
  levelBadge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#342846',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#342846',
    zIndex: 3,
    position: 'relative',
  },
  levelBadgeHighlight: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#E6D5F5',
    position: 'absolute',
    zIndex: 1,
    opacity: 0.5,
    top: -8,
    left: -8,
  },
  levelBadgeNumber: {
    ...HeadingStyle,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    zIndex: 4,
  },
  levelContent: {
    flex: 1,
    paddingTop: 4,
  },
  levelHeading: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 18,
    marginBottom: 4,
  },
  levelSubheading: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
    opacity: 0.7,
    lineHeight: 20,
  },
  finalStarContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
    marginBottom: 40,
    marginLeft: 0,
    marginRight: 16,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 20, // Minimum 20px padding (was 0)
    paddingRight: 20, // Minimum 20px padding (was 0)
    position: 'relative',
    zIndex: 2,
    width: 48,
    height: 24,
    alignSelf: 'flex-start',
  },
  finalStarWrapper: {
    transform: [{ translateY: 5 }],
  },
  finalStarEmoji: {
    fontSize: 24,
    textAlign: 'center',
    lineHeight: 24,
    margin: 0,
    padding: 0,
  },
  goalLabelTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    marginLeft: 0,
  },
  goalStarEmoji: {
    fontSize: 18,
    marginRight: 8,
  },
  goalLabelText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 18,
    paddingTop: 20,
  },
  goalStepWrapper: {
    width: '100%',
    position: 'relative',
    marginBottom: 8,
  },
  goalStepItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
    minHeight: 32,
  },
  goalStepLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
    minWidth: 60,
    height: 32,
  },
  checkmarkContainer: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkmarkWrapper: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  animatedCheckmark: {
    fontSize: 24,
    color: '#342846', // Blue color
    fontWeight: 'bold',
  },
  checkmarkPlaceholder: {
    width: 32,
    height: 32,
  },
  goalStepNumber: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    fontWeight: 'bold',
    marginRight: 8,
    minWidth: 20,
    textAlign: 'right',
  },
  goalStepText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    flex: 1,
  },
  startContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    marginLeft: 0,
  },
  startBulbContainer: {
    marginRight: 8,
  },
  startBulb: {
    fontSize: 18,
  },
  startText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    paddingBottom: 20,
  },
  whatYouGetTitle: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 20,
    marginTop: 40,
    marginBottom: 24,
    textAlign: 'center',
  },
  cardsContainer: {
    width: width - 50,
    height: 280,
    marginBottom: 20,
    overflow: 'hidden',
    alignSelf: 'center',
    position: 'relative',
  },
  cardsWrapper: {
    flexDirection: 'row',
    height: '100%',
  },
  benefitCard: {
    width: width - 50,
    paddingHorizontal: 35,
    paddingTop: 28,
    paddingBottom: 28,
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    justifyContent: 'center',
    flexShrink: 0,
    overflow: 'hidden',
  },
  benefitCardImage: {
    borderRadius: 8,
    resizeMode: 'cover',
  },
  benefitCardHeading: {
    ...HeadingStyle,
    color: '#FFFFFF',
    fontSize: 17,
    marginBottom: 10,
    textAlign: 'center',
    lineHeight: 22,
  },
  benefitCardBody: {
    ...BodyStyle,
    color: '#FFFFFF',
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  cardIndicators: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    gap: 12,
  },
  cardIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#342846',
  },
  cardIndicatorActive: {
    backgroundColor: '#baccd7',
    borderColor: '#342846',
  },
  paywallContinueButton: {
    backgroundColor: '#342846',
    borderRadius: 999,
    paddingVertical: 16,
    paddingHorizontal: 40,
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    marginHorizontal: 20,
    marginBottom: 40,
    zIndex: 1000,
  },
  paywallContinueButtonText: {
    ...ButtonHeadingStyle,
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  customPathFormContent: {
    paddingHorizontal: 40,
    paddingTop: 0,
    paddingBottom: 100,
  },
  customPathHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingBottom: 20,
    position: 'relative',
  },
  customPathHeaderTitle: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  customPathBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#342846',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: 40,
    top: '50%',
    marginTop: -20,
  },
  customPathHelperButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#342846',
    position: 'absolute',
    right: 40,
    top: '50%',
    marginTop: -20,
  },
  customPathAppHeadingCard: {
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 32,
    paddingHorizontal: 20,
    paddingVertical: 16,
    // Purple 3D shadow
    shadowColor: '#342846',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.6,
    shadowRadius: 16,
    elevation: 12, // For Android
  },
  customPathAppHeading: {
    ...BodyStyle,
    color: '#FFFFFF',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  purpleBackgroundImage: {
    borderRadius: 8,
    resizeMode: 'cover',
  },
  fieldError: {
    borderColor: '#FF0000',
    borderWidth: 1,
  },
  fieldErrorText: {
    ...BodyStyle,
    color: '#FF0000',
    fontSize: 12,
    marginTop: 4,
  },
  textArea: {
    minHeight: 120,
    paddingTop: 12,
  },
  radioButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    paddingVertical: 4,
  },
  radioButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#342846',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioButtonInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#342846',
  },
  radioButtonLabel: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
    flex: 1,
  },
  assistanceTextContainer: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 20,
    marginHorizontal: 40,
    maxWidth: '80%',
    borderWidth: 1,
    borderColor: '#342846',
  },
  customPathFormSubtitle: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
    textAlign: 'center',
    marginTop: -55,
    marginBottom: 32,
    opacity: 0.8,
  },
  customPathFieldContainer: {
    marginBottom: 32,
    position: 'relative',
  },
  customPathLabelWithHelper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  customPathHelperIcon: {
    padding: 4,
    marginLeft: 8,
  },
  customPathFieldLabel: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 16,
    textAlign: 'center',
  },
  customPathFieldHelper: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 12,
    marginBottom: 12,
    opacity: 0.7,
    lineHeight: 16,
  },
  customPathDropdownWrapper: {
    position: 'relative',
    zIndex: 10,
    marginTop: 8,
  },
  customPathDropdownButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 50,
    flexWrap: 'wrap',
    // Purple 3D shadow
    shadowColor: '#342846',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.6,
    shadowRadius: 16,
    elevation: 12, // For Android
  },
  customPathDropdownText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    flex: 1,
    flexShrink: 1,
  },
  customPathDropdownPlaceholder: {
    color: '#999',
    opacity: 0.7,
  },
  customPathDropdownArrow: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 12,
    marginLeft: 8,
  },
  customPathDropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    marginTop: 4,
    zIndex: 1000,
    maxHeight: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  customGoalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#342846',
    padding: 20,
    marginBottom: 20,
  },
  customGoalCardTitle: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 18,
    marginBottom: 20,
    textAlign: 'left',
  },
  coreObjectiveTitle: {
    textAlign: 'center',
  },
  centeredCardTitle: {
    textAlign: 'center',
  },
  customGoalFieldContainer: {
    marginBottom: 24,
  },
  customGoalFieldLabel: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 16,
    marginBottom: 8,
    textAlign: 'left',
  },
  customGoalFieldHelper: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 12,
    marginBottom: 12,
    opacity: 0.7,
    lineHeight: 16,
  },
  milestoneCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    position: 'relative',
  },
  milestoneTitleContainer: {
    flex: 1,
    alignItems: 'center',
  },
  adviceButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#342846',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  adviceModal: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#342846',
  },
  adviceText: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
    lineHeight: 20,
  },
  addMilestoneButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: '#342846',
    marginTop: 8,
  },
  addMilestoneButtonText: {
    ...BodyStyle,
    color: '#fff',
    fontSize: 14,
    marginLeft: 8,
    fontWeight: '600',
  },
  establishGoalButton: {
    backgroundColor: '#342846',
    borderRadius: 999,
    paddingVertical: 16,
    paddingHorizontal: 40,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 16,
  },
  establishGoalButtonText: {
    ...ButtonHeadingStyle,
    color: '#fff',
    fontSize: 18,
  },
  obstaclePageContent: {
    paddingHorizontal: 40,
    paddingTop: 40,
    paddingBottom: 120, // Increased to accommodate absolutely positioned button
    alignItems: 'center',
  },
  obstaclePageTitle: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 24,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  obstaclePageSubtext: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 32,
    paddingHorizontal: 20,
    lineHeight: 22,
    opacity: 0.8,
  },
  obstacleFieldContainer: {
    width: '100%',
    marginBottom: 32,
  },
  obstacleTextField: {
    minHeight: 150,
    paddingTop: 10, // Increased by 4px to move text down
    paddingBottom: 14, // Decreased by 4px to maintain spacing
    includeFontPadding: false, // Prevent extra padding on Android
  },
  obstacleContinueButton: {
    alignItems: 'center',
    backgroundColor: '#342846',
    borderRadius: 999,
    paddingVertical: 16,
    paddingHorizontal: 40,
    alignSelf: 'center',
    minWidth: 200,
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    zIndex: 1000,
  },
  obstacleContinueButtonDisabled: {
    backgroundColor: '#D0D0D0',
    opacity: 0.6,
  },
  obstacleContinueButtonText: {
    ...ButtonHeadingStyle,
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  goalQuote: {
    ...BodyStyle,
    color: '#342846',
    fontSize: 14,
    fontStyle: 'italic',
    textAlign: 'center',
    opacity: 0.8,
    marginBottom: 40,
    paddingHorizontal: 20,
  },
  milestoneInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  milestoneNumberIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#342846',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  milestoneNumberText: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 18,
    fontWeight: 'bold',
  },
  milestoneTextFieldWrapper: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    minHeight: 90,
  },
  milestoneTextField: {
    width: '100%',
    textAlignVertical: 'center', // Center align text vertically
    includeFontPadding: false, // Prevent extra padding on Android
  },
  question: {
    ...HeadingStyle,
    color: '#342846',
    fontSize: 18,
    flex: 1,
    textAlign: 'left',
  },
  bodyText: {
    ...BodyStyle,
    color: '#342846',
    marginBottom: 20,
    fontSize: 12,
    width: '100%',
    textAlign: 'left',
    opacity: 0.7,
    lineHeight: 16,
  },
  answerField: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#342846',
    borderRadius: 8,
    overflow: 'visible',
    marginBottom: 32,
    minHeight: 130,
    width: '100%',
    alignSelf: 'flex-start',
    marginTop: 16,
    shadowColor: '#342846',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  answerInput: {
    ...BodyStyle,
    paddingHorizontal: 20,
    paddingTop: 10, // Increased by 4px to move text down
    paddingBottom: 14, // Decreased by 4px to maintain spacing
    color: '#342846',
    fontSize: 14,
    minHeight: 130,
    textAlignVertical: 'top',
    lineHeight: 16, // Reduced lineHeight to match fontSize more closely (was 20)
    includeFontPadding: false, // Prevent extra padding on Android
  },
  lightBulbEmoji: {
    fontSize: 24,
  },
  assistanceModal: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#342846',
    marginTop: 8,
  },
  closeAssistanceButton: {
    alignSelf: 'flex-end',
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  closeAssistanceButtonText: {
    fontSize: 24,
    color: '#342846',
    fontWeight: 'bold',
  },
  // Life Context Styles
  lifeContextContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  lifeContextLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lifeContextLoadingText: {
    ...BodyStyle,
    color: '#666',
  },
  lifeContextHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    gap: 12,
  },
  lifeContextHeaderButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lifeContextProgressBarContainer: {
    flex: 1,
    height: 6,
  },
  lifeContextProgressBarBg: {
    flex: 1,
    backgroundColor: 'rgba(52, 40, 70, 0.1)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  lifeContextProgressBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  lifeContextTitleSection: {
    alignItems: 'center',
    paddingHorizontal: 28,
    paddingTop: 16,
  },
  lifeContextMainTitle: {
    ...HeadingStyle,
    fontSize: 24,
    color: '#342846',
    textAlign: 'center',
    marginBottom: 8,
  },
  lifeContextMainSubtitle: {
    ...BodyStyle,
    fontSize: 15,
    color: '#666',
    textAlign: 'center',
    lineHeight: 20,
    marginTop: 5,
  },
  lifeContextVisualArea: {
    height: 90,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15,
    marginBottom: 12,
  },
  lifeContextVisualSwitcher: {
    width: 105,
    height: 90,
    position: 'relative',
  },
  lifeContextVisualItem: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lifeContextVisualContainer: {
    width: 105,
    height: 90,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lifeContextMainIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
  },
  lifeContextPathLine: {
    position: 'absolute',
    width: 45,
    height: 3,
    borderRadius: 2,
    left: 52.5,
  },
  lifeContextCrackLine: {
    position: 'absolute',
    width: 3,
    height: 15,
    backgroundColor: '#bfacca',
    borderRadius: 2,
  },
  lifeContextConstellationStar: {
    position: 'absolute',
  },
  lifeContextGlowCircle: {
    position: 'absolute',
    width: 54,
    height: 54,
    borderRadius: 27,
  },
  lifeContextStepIndicator: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 25,
    marginBottom: 12,
  },
  lifeContextStepDot: {
    height: 8,
    borderRadius: 4,
  },
  lifeContextCarouselContainer: {
    width: '100%',
    marginTop: -30,
    marginBottom: 10,
  },
  lifeContextArrowContainer: {
    width: '100%',
  },
  lifeContextSwipeIndicators: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 28,
  },
  lifeContextArrowPlaceholder: {
    width: 24,
    height: 24,
  },
  lifeContextArrowLeft: {
    opacity: 0.7,
  },
  lifeContextArrowRight: {
    opacity: 0.7,
  },
  lifeContextContinueButton: {
    backgroundColor: '#342846',
    borderRadius: 999,
    paddingVertical: 16,
    paddingHorizontal: 40,
    minWidth: 200,
    alignItems: 'center',
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    zIndex: 1000,
  },
  lifeContextContinueButtonText: {
    ...ButtonHeadingStyle,
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  lifeContextContinueButtonDisabled: {
    backgroundColor: 'rgba(52, 40, 70, 0.4)',
    opacity: 0.6,
  },
  lifeContextContinueButtonTextDisabled: {
    color: 'rgba(255, 255, 255, 0.7)',
  },
  lifeContextCardWrapper: {
    width: width,
    paddingHorizontal: 12,
    paddingBottom: 15,
  },
  lifeContextQuestionCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 24,
    paddingTop: 20,
    paddingBottom: 20,
    paddingHorizontal: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 5,
    flexDirection: 'column',
  },
  lifeContextQuestionCardShort: {
    alignSelf: 'center',
    marginTop: 20,
  },
  lifeContextQuestionCardMulti: {
    marginTop: 20,
    maxHeight: 400,
    overflow: 'hidden',
  },
  lifeContextQuestionText: {
    ...HeadingStyle,
    fontSize: 18,
    color: '#342846',
    textAlign: 'center',
    marginBottom: 8,
  },
  lifeContextSubtitleText: {
    ...BodyStyle,
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 16,
  },
  lifeContextOptionsContainer: {
    gap: 15,
  },
  lifeContextOptionsContainerMulti: {
    alignItems: 'stretch',
    gap: 15,
    paddingBottom: 10,
  },
  lifeContextOptionsContainerMultiPad: {
    alignItems: 'stretch',
    width: '100%',
  },
  lifeContextOptionsGridContainer: {
    paddingBottom: 8,
  },
  lifeContextOptionsGridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    padding: 24
  },
  lifeContextOptionsGridColumn: {
    flex: 1,
    gap:10 
  },
  lifeContextOptionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: 'rgba(52, 40, 70, 0.15)',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    gap: 6,
    minHeight: 50,
    height: 50,
    width: '100%',
  },
  lifeContextOptionWrapperMulti: {
    alignItems: 'stretch',
    justifyContent: 'center',
    marginBottom: 15,
    width: '100%',
  },
  lifeContextOptionWrapperMultiPad: {
    width: '100%',
    alignItems: 'stretch',
  },
  lifeContextOptionButtonMulti: {
    width: '100%',
    maxWidth: '100%',
    alignSelf: 'stretch',
  },
  lifeContextOptionButtonInsideMulti: {
    width: '100%',
  },
  lifeContextOptionsWrapper: {
    position: 'relative',
    width: '100%',
    alignItems: 'stretch',
    paddingHorizontal: 0,
    overflow: 'hidden',
    flexShrink: 1,
  },
  lifeContextOptionsScroll: {
    height: 280,
    width: '100%',
    alignSelf: 'stretch',
  },
  lifeContextScrollIndicator: {
    position: 'absolute',
    right: 12,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    pointerEvents: 'none',
  },
  lifeContextScrollDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#342846',
    opacity: 0.3,
  },
  lifeContextOptionButtonGrid: {
    paddingHorizontal: 8,
    paddingVertical: 12,
    minWidth: 0,
    flex: 1,
    minHeight: 48,
  },
  lifeContextOptionText: {
    ...BodyStyle,
    fontSize: 13,
    color: '#342846',
    textAlign: 'center',
    flex: 1,
  },
  lifeContextOptionTextSelected: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  lifeContextOptionSelectedSoft: {
    backgroundColor: 'rgba(186, 172, 202, 0.45)',
    borderColor: '#342846',
  },
  lifeContextOptionTextSelectedSoft: {
    color: '#342846',
    fontWeight: '600',
  },
  lifeContextOptionTextTight: {
    lineHeight: 18,
  },
  lifeContextSelectionCount: {
    ...BodyStyle,
    fontSize: 13,
    color: '#666',
    textAlign: 'center',
    marginTop: 12,
    marginBottom: 0,
  },
  lifeContextBottomNav: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 16,
    gap: 12,
  },
  lifeContextBackButtonNav: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 30,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(52, 40, 70, 0.1)',
    gap: 6,
  },
  lifeContextBackButtonText: {
    ...BodyStyle,
    fontSize: 15,
    color: '#342846',
  },
  lifeContextNextButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 30,
    gap: 8,
  },
  lifeContextNextButtonText: {
    ...BodyStyle,
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  lifeContextHintContainer: {
    alignItems: 'center',
    paddingTop: 16,
  },
  lifeContextHintText: {
    ...BodyStyle,
    fontSize: 14,
    color: '#999',
  },
});
